### ISSUE TITLE
Down Syndrome collective ticket

### ISSUE THREAD

**Issue by elv-sb** [monarch-initiative/mondo#5109] opened 2022-06-28 22:57 UTC
As discussed during our weekly meeting here are the terms that need to be added to the ontology. Regarding the karyotypes, some of them might be too detailed for MONDO, so we need a list of what can not be added.

Thank you!

**Preferred term label:**

Balanced Robertsonian translocation
Unbalanced Robertsonian translocation

**Karyotypes**
47, XX, +21
47,XX,+21
47, XY +21
47, XX +21
47,XY,+21
47,XX +21
46,XY/ 47,XY,+21
47, XY, +21
46,XY,der(14;21)(q10;q10),+21
47,XY, +21
46,XY,+21, t(13;14)
47,XX, +21
46,XX,der(3)t(3;21)(p25;q11.2)
47,XX+21
47xy
47 XX, +21
47,XX.21+
47, XY+21
46,XY,der(13;21)(q10;q10)+21
47, XX

**Comment by nicolevasilevsky** [comment] 2022-06-28 22:58
Thanks @elv-sb!

**Comment by nicolevasilevsky** [comment] 2022-06-28 23:07
@sabrinatoro some potentially helpful resources:

- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7048690/
- Robertsonian Translocation is in NCIT: https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C28447

**Comment by sabrinatoro** [comment] 2022-06-30 17:56
@elv-sb Thank you for your request. 
Could you please review the proposed definitions below? I also have some questions to make sure the terms and their classifications are correct. Thank you in advance! 

Proposed definitions: 
**Robertsonian translocation** is a chromosomal disorder in which two acrocentric chromosomes break, resulting in the fusion of the nonhomologous chromosomes’ long arms to form a single, large chromosome. (PMID, NCIT)

**Balanced Robertsonian translocation** is a Robertsonian translocation in which translocation displacement of the end regions of chromosomes occurs without loss of chromosomal material between the two nonhomologous chromosomes. 
(PMID)

**Unbalanced Robertsonian translocation** is a Robertsonian translocation in which translocation displacement of the end regions of chromosomes occurs with loss of chromosomal material between the two nonhomologous chromosomes. 
(PMID)

**Robertsonian translocation Down syndrome** is a Robertsonian translocation in which _(part or complete ??)_ chromosome 21 is attached to another chromosome, resulting in the presence of a third copy of chromosome 21 genetic material. 

Questions: 
- Is translocation Down syndrome ([MONDO:0700128](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0700128)) the same as Robertsonian translocation affecting Chromosome 21?  Is there translocation of chr21 which are not Robertsonian? 
- Does Robertsonian translocation affect the full, part, or either full or part of  Chromosome 21?
- I am a bit confused with regards to the karyotypes. Does the chromosome to which Chr21 is attached matter in terms of the disease term? Should we create specific terms for when Chr21 is attached to chromosome 14 or 13,...?
Thank you!

**Comment by elv-sb** [comment] 2022-07-05 12:34
@sabrinatoro thank you for the quick reply

From what I have found (https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/robertsonian-translocation#:~:text=A%20Robertsonian%20translocation%20is%20one,that%20predispose%20to%20their%20fusion.) Robertsonian translocation is different from MONDO:0700128

As for your last question, there can be instances when it matters, but I do not know if this level of detail is out of scope for MONDO.

Thank you!

**Comment by nicolevasilevsky** [comment] 2022-07-05 23:12
From the [INCLUDE data coordianting center Data Modeling](https://docs.google.com/document/d/1iAEG8oPwsN304xh8EuqdOFTFu5PaEx8ZsWXcUwuoetA/edit#) call:  'Robertsonian translocation' is a partial or extra copy of the chromosome 21 has been added somewhere else ('stuck' to a different chromosome - any of them).

**Comment by sabrinatoro** [comment] 2022-07-13 22:00
Thank you @elv-sb and @nicolevasilevsky 

Please see the proposal below, but first, some considerations: 
- according to Wikipedia (I need a better reference):  
In genetics, chromosome translocation is a phenomenon that results in unusual rearrangement of chromosomes. This includes balanced and unbalanced translocation, **with two main types: reciprocal-, and Robertsonian translocation.** **Reciprocal translocation** is a chromosome abnormality caused by exchange of parts between non-homologous chromosomes. Two detached fragments of two different chromosomes are switched. **Robertsonian translocation** occurs when two non-homologous chromosomes get attached, meaning that given two healthy pairs of chromosomes, one of each pair "sticks" and blends together homogeneously.[1]
- Based on this, 'translocation Down syndrome' (MONDO:0700128) should be updated (ie remove exact synonym) and be the parent of the new term "Robertsonian Translocation Down syndrome", and 'reciprocal translocation Down syndrome' ([PMID:[134161](https://pubmed.ncbi.nlm.nih.gov/134161)
- note: the definition of Down Syndrome should be updated to : Down syndrome is a chromosomal disorder caused by the presence of a third (partial or total) copy of chromosome 21 **genetic material**.     

**Hierarchy proposal:** 
-Down syndrome
---translocation Down syndrome (MONDO:0700128)
-----Robertsonian translocation Down syndrome (= robertsonian translocation in which chromosome 21 (part or full) is “stuck” to another chromosome)
----------Balanced Robertsonian translocation Down syndrome
----------Unbalanced Robertsonian translocation Down syndrome
-----reciprocal translocation down syndrome (= reciprocal translocation in which chr 21 material has been exchanged with another chr)

Please let me know what you think.

**Comment by sabrinatoro** [comment] 2022-07-14 17:35
_Discussed on the Mondo curation call on 22-07-14:_
Question: should we add the general translocation terms?
-Chromosomal disorder due to chromosome translocation
---Robertsonian translocation (= any chromosome stuck to other chromosome)
------Balanced Robertsonian translocation
------Unbalanced Robertsonian translocation
---reciprocal translocation
------Balanced reciprocal translocation
------Unbalanced reciprocal translocation
It is unclear whether there are/will be diseases involving other chromosome translocation to be added into Mondo. Therefore, for the moment, we will only add the Down Syndrome-related translocation disorders and reassess if/when diseases due to other chromosome translocations are needed.

**Comment by nicolevasilevsky** [comment] 2022-07-20 00:21
@sabrinatoro did we decide not to add the specific karyotypes?

**Comment by nicolevasilevsky** [comment] 2022-07-20 00:22
and I see you did not add Balanced reciprocal translocation and Unbalanced reciprocal translocation on your PR, did you not want to add those?

**Comment by sabrinatoro** [comment] 2022-07-20 00:39
@nicolevasilevsky 
I don't think we can add the karyotypes at this point, but if it is something that is needed (ie a specific down syndrome with a specific karyotype), we can discuss strategies. As of now, it seems a bit too specific. 

I did not add balanced/unbalanced reciprocal translocation because reciprocal translocation was not requested. I added "reciprocal" because it helps understand that there are 2 types of translocation and I found evidence for it in the literature. I however didn't find pubs to warrant created terms for balanced/unbalanced reciprocal translocation, and therefore I did not add these terms. HOWEVER, it would be easy enough to add them if we need them, and in this case, we would just have definitions made based on chromosome translocation type involving chr 21. Let me know if we should add these or not.

**Comment by nicolevasilevsky** [comment] 2022-07-20 00:44
sounds good, thanks @sabrinatoro! @elv-sb let us know if you would like us to add Balanced reciprocal translocation and Unbalanced reciprocal translocation. Otherwise, i don't think we need to add them at this time @sabrinatoro 

@elv-sb please let us know if you need the specific karyotype terms. I will merge Sabrina's PR that adds the terms belowand that will close this ticket but please reopen if needed, thanks! :)

- id: MONDO:0700082
name: Robertsonian translocation Down syndrome

- id: MONDO:0700083
name: reciprocal translocation down syndrome

- id: MONDO:0700093
name: balanced Robertsonian translocation Down syndrome

- id: MONDO:0700094
name: unbalanced Robertsonian translocation Down syndrome

**Closed** 2022-07-20 00:44 UTC
Labels: New term request, user request
