### ISSUE TITLE
New disease Term overgrowth syndrome w/or without cerebral malformations[NTR]

### ISSUE THREAD

**Issue by abbe-Lai** [monarch-initiative/mondo#1830] opened 2020-07-27 22:03 UTC
**Preferred term label:**
Overgrowth syndrome w/or without cerebral malformations

**Synonyms**

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)**
This disorder term will be used for several genes within the MTOR pathway (MTOR, PIK3CA, PIK3R2, AKT3). These genes result in very similar overlapping phenotypes which are often indistinguishable. Depending on where the somatic mutation occurs it can result in overgrowth in the brain or of a single limb or multiple limbs. Many of the diseases listed in OMIM under these genes are actually a spectrum of mosaicism. (PMID: 30197175, 28969385). 

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)*
Congenital Abnormality
Developmental abnormality during embryogenesis
overgrowth/obesity syndrome
**Children terms (if applicable)** Should any existing terms that should be moved underneath this new proposed term?

**Your nano-attribution (ORCID)**
Brain Malformation Curation Expert Panel

**Comment by nicolevasilevsky** [comment] 2020-08-11 16:10
@abbe-Lai
> Many of the diseases listed in OMIM under these genes are actually a spectrum of mosaicism. 

Should any of these OMIM terms be a child of this term?

**Comment by nicolevasilevsky** [comment] 2020-09-03 23:21
Hi @abbe-Lai pinging you again - see question above. Thanks!

**Comment by nicolevasilevsky** [comment] 2020-09-03 23:39
@abbe-Lai 
Is this proposed label and def okay:

label:
'overgrowth syndrome with or without cerebral malformations due to defects in MTOR pathway'

def:
An overgrowth syndrome caused by variations in genes within the MTOR pathway (MTOR, PIK3CA, PIK3R2, AKT3), which can either result in overgrowth in the brain or of a single limb or multiple limbs.

**Comment by nicolevasilevsky** [comment] 2020-11-17 01:44
@abbe-Lai following up, please let me know if the proposed label and definition above look okay, whenever you have a chance. Thanks!

**Comment by abbe-Lai** [comment] 2020-11-17 03:48
Hello,

We have come up with a new idea! Should I submit it in a new github ticket? The majority of our panel members have decided that a single term would be sufficient.

Best,
Abbe Lai

**Comment by nicolevasilevsky** [comment] 2020-11-17 04:43
Great - a new ticket is great, I'll close this one, thanks!

**Closed by nicolevasilevsky** 2020-11-17 04:43 UTC
Labels: New term request, high priority, question
