### ISSUE TITLE
Revise classification of MONDO:0044013 'puerperal disorder'

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#652] opened 2019-03-26 12:05 UTC
MONDO:0044013 'puerperal disorder' is a subclass of 'pregnancy disorder'.
But pregnancy goes from conception to birth, while puerperium covers the six-to-eight-week period after birth.
I was going to suggest that 'puerperal disorder' should be a subclass of 'female reproductive system disease' instead, but puerperal disorders cover other areas too (see e.g. its children 'postpartum psychosis' and 'postpartum thyroiditis'). So I'm not sure what broader parent would work for 'puerperal disorder', other than the top-level 'disease or disorder'... I can't see any of the existing terms being appropriate. On the other hand, grouping disorders that occur during that time might be useful from a medical perspective. 
Suggestions please? 
(EFO has the same issue, but our 'puerperal disorder' was modelled after yours ;-) )

**Comment by cmungall** [comment] 2019-03-29 01:15
Maybe define pregnancy disorder more generally, to include during or having a causal link to?

**Comment by paolaroncaglia** [comment] 2019-04-14 13:06
@cmungall I opened a ticket for EFO so we can come back to this. Thanks.

**Comment by nicolevasilevsky** [comment] 2019-05-01 23:25
@cmungall - @paolaroncaglia and others discussed this when we met earlier this week - it seems like some of the subclasses of pregnancy disorder are not proper children of 'female reproductive system disease' (which is a disease with a location in the female reproductive system).

For example, 'gestational diabetes' is not located in the female reproductive system, or 'chorea gravidarum'.

I suggest we revise the text def of pregnancy disorder and reclassify it to a child of 'disease or disorder'.

**Comment by nicolevasilevsky** [comment] 2019-05-21 01:08
@cmungall and @pnrobinson any objections to my comment above?

**Comment by pnrobinson** [comment] 2019-05-21 01:34
@nicolevasilevsky @cmungall  The difficulty is that if we want to define diseases "logically" there will be a massive and inconsistent hierarchy. Having superclasses such as pregnancy disorder make things difficult because there is no specialist for puerperal disorders -- all of this is the obstetrician. 
So, definitely the subclass relations above should be fixed as you propose.
Having a superclass such as pregnancy disorder may not be the best strategy.

**Comment by paolaroncaglia** [comment] 2019-05-22 08:49
@pnrobinson @nicolevasilevsky @cmungall
I agree that trying to define logically a superclass for ‘pregnancy disorder’ or ‘puerperal disorder’ is not straightforward. I also agree that both EFO and MONDO should correct some of the current subclass relationships if these are wrong, and/or add new ones where needed. However, EFO would want to retain ‘pregnancy disorder’ and ‘puerperal disorder’ as grouping classes, because our main users need to refer to (some) ICD10 classes, so we have created terms and mappings in EFO for them, and the ICD10 branch for ‘Pregnancy, childbirth and the puerperium’ (https://icd.who.int/browse10/2016/en#/XV) is one of those cases. I’ll outline a strategy for EFO in our tracker (https://github.com/EBISPOT/efo/issues/417), and MONDO may choose to follow the same or diverge, though of course I hope our strategy may be of use to you too. :-) Thanks!

**Comment by nicolevasilevsky** [comment] 2019-06-21 17:01
@cmungall should we follow EFO's proposal (https://github.com/EBISPOT/efo/issues/417)? If yes, I can work on implementing this in Mondo

**Comment by nicolevasilevsky** [comment] 2019-08-15 21:55
@paolaroncaglia I am reading through this thread and https://github.com/EBISPOT/efo/issues/490 and want to clarify what the action items are:

Should Mondo create a new term 'perinatal condition' (per https://github.com/EBISPOT/efo/issues/490) and 'puerperal disorder' should be reclassified as a child of this term?

Should 'pregnancy disorder' be a child of 'disease or disorder'?

Thanks!

**Comment by paolaroncaglia** [comment] 2019-08-20 11:07
@nicolevasilevsky 
Thanks for following up. In reply to your questions:

"Should Mondo create a new term 'perinatal condition' (per EBISPOT/efo#490)"
Yes please. I plan to create an EFO term for that, today or tomorrow, so please check back on EBISPOT/efo#490 to facilitate alignment/mapping.

"and 'puerperal disorder' should be reclassified as a child of this term?"
No please :-) 'perinatal condition' will refer to unborn or newly born child, while 'puerperal disorder' refers to maternal issues. Our plan is to move 'puerperal disorder' to be a direct subclass of 'disease', because pregnancy and puerperium don't overlap in time. We may end up having an EFO uberclass for 'Pregnancy, puerperium and perinatal conditions' (or similarly named), with each of the 3 under it, but, due to our main users' current needs, in any case we'd rather not have 'puerperal disorder' as a subclass of 'pregnancy disorder'.

"Should 'pregnancy disorder' be a child of 'disease or disorder'?"
Yes please.

Ideally we should synchronize the changes in EFO and MONDO, to avoid inconsistency post-release(s). I'll see if I can edit EFO before I leave for a short trip + bank holiday (away from my desk 22-29 August), and will update EBISPOT/efo#490 accordingly. Many thanks for your work.

**Comment by nicolevasilevsky** [comment] 2019-08-20 16:44
Thanks for the clarification @paolaroncaglia! I'll wait until you have updated this ticket (https://github.com/EBISPOT/efo/issues/490), then I will follow your workflow.

**Comment by paolaroncaglia** [comment] 2019-08-21 10:02
@nicolevasilevsky 
To make a long story short: I started editing for EBISPOT/efo#490 but ran into issues that require a bit of time and help from others to address. Due to holiday plans, I'll need to postpone this to the wc Sept 2nd. Thanks and speak then!

**Comment by nicolevasilevsky** [comment] 2019-08-21 15:58
No problem, enjoy your holiday!

**Comment by paolaroncaglia** [comment] 2019-08-30 15:19
@pnrobinson 
The wording was suggested by our collaborators according to MedDRA and NCIT (http://bioportal.bioontology.org/ontologies/MEDDRA?p=classes&conceptid=10036585 and http://purl.obolibrary.org/obo/NCIT_C49404), but I agree that we could (should) label it 'perinatal disease' rather than 'condition', and keep 'condition' in a synonym. I'll make a note in the EFO ticket. Thanks!

**Comment by paolaroncaglia** [comment] 2019-09-24 13:08
@nicolevasilevsky 
FYI, these edits are still pending from the EFO side, I'll keep you posted when we implement them.

**Comment by paolaroncaglia** [comment] 2019-10-16 12:57
@nicolevasilevsky 
An update on this ticket. To make a long story short, when I tried doing the edits above in EFO, @zoependlington and I realized that, because of the Mondo mappings, we need to hack too many things in place. These were particularly difficult cases because we wish to change terms' placement to be higher up under 'disease', and because the Mondo matches have children themselves. So it'd be simpler and, above all, less error-rone if Mondo could please do the edits first. To recap, these were (and we had agreed on them previously):

- [ ] Move MONDO:0044013 'puerperal disorder' from being a subclass of 'pregnancy disorder' to being a direct child of 'disease or disorder'
- [ ] Move MONDO:0024575 'pregnancy disorder' from being a subclass of 'female reproductive system disease' to being a direct child of 'disease or disorder'

Nothing else would be needed from Mondo at this stage, although (not urgent) you might want to 
- [ ] Revise the following subclasses:
MONDO:0044014 postpartum thyroiditis
subclass of 'autoimmune disease of urogenital tract'
subclass of 'autoimmune thyroid disease'
Based on the definition, is there really support for references to autoimmune and urogenital tract?
- [ ] MONDO:0044014 postpartum thyroiditis also has the following xref which doesn't look correct, not sure how it ended there:
http://purl.obolibrary.org/obo/EFO_1001428
'Subacute Combined Degeneration'
"A neuropathy due to VITAMIN B 12 DEFICIENCY or to excessive NITROUS OXIDE inhalation. It is associated with overproduction of the myelinolytic TUMOR NECROSIS FACTOR-ALPHA."
Looks like it should be removed.

Many thanks,
Paola and Zoe

**Comment by paolaroncaglia** [comment] 2019-11-13 09:17
@nicolevasilevsky 
Sorry to ask, but could you please implement the changes agreed/suggested in https://github.com/monarch-initiative/mondo/issues/652#issuecomment-542686898? It would be greatly helpful for EFO as we're sort of stuck otherwise (FYI, see the UPDATE at the end of this comment: https://github.com/EBISPOT/efo/issues/490#issuecomment-542625059).
Many thanks,
Paola

**Comment by nicolevasilevsky** [comment] 2019-11-13 15:40
No need to apologize @paolaroncaglia, thanks for the nudge. I tagged this with our new milestone "December release".

Regarding MONDO:0044014 postpartum thyroiditis:
I revised the text def to include text from the MeSH text def, which does suggest it is an autoimmune disease.

**Comment by nicolevasilevsky** [comment] 2019-11-13 15:42
I deleted the xref to EFO_1001428, it does seem wrong

**Closed** 2019-11-14 01:26 UTC
Labels: EFO, pending PR, question
