### ISSUE TITLE
[Obsolete] 'chorea minor'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#2749] opened 2021-02-28 18:34 UTC
**Mondo term (ID and Label)**
'chorea minor'

**Reason for deprecation**
obsoleted in GARD
cc @galyea-gard

**Suggested term to consider**
http://purl.obolibrary.org/obo/MONDO_0001595
'choreatic disease'

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by galyea-gard** [comment] 2021-03-01 15:36
Hi Nicole! Minor chorea was retired because it was duplicate of Sydenham's chorea; in addition, this synonym (minor chorea)  is currently not used anymore. Thank you! Gioconda

**Closed** 2021-03-17 18:39 UTC
Labels: obsolete
