### ISSUE TITLE
split POAG

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#2507] opened 2021-01-14 00:57 UTC
MONDO:0007665 conflates the generic POAG with a gene-specific form; in that it follows https://omim.org/entry/137760

from that entry:

Other forms of primary open angle glaucoma include GLC1A (137750), caused by mutation in the MYOC gene (601652) on chromosome 1q24; GLC1B (606689) on chromosome 2cen-q13; GLC1C (601682) on chromosome 3q21-q24; GLC1D (602429) on chromosome 8q23; GLC1F (603383), caused by mutation in the ASB10 gene on chromosome 7q36; GLC1G (609887), caused by mutation in the WDR36 gene (609669) on chromosome 5q22; GLC1H (611276) on chromosome 2p16-p15; GLC1I (609745) on chromosome 15q11-q13; GLC1J (608695) on chromosome 9q22; GLC1K (608696) on chromosome 20p12; GLC1L (see 137750) on chromosome 3p22-p21; GLC1M (610535) on chromosome 5q22; GLC1N (611274) on chromosome 15q22-q24; GLC1O (613100), caused by mutation in the NTF4 gene (162662) on chromosome 19q13; GLC1P (177700), caused by an approximately 300-kb duplication on chromosome 12q24, most likely involving the TBK1 gene (604834).

**Comment by sabrinatoro** [comment] 2021-07-30 18:39
OMIM:137760 refers to the particular disease called 'primary open angle glaucoma' (MONDO:0007665)-referring to mutation in OPTN

>Other forms of primary open angle glaucoma include GLC1A (137750), caused by mutation in the MYOC gene (601652)  ....

All these OMIM terms have their own record in Mondo, and are grouped (with POAG, MONDO:0007665) under 'open-angle glaucoma' (MONDO:0005338) and 'hereditary glaucoma' (MONDO:0018174)

I think that no change should be made to this term. 
@nicolevasilevsky, do you agree?

**Comment by sabrinatoro** [comment] 2021-09-15 20:39
@nicolevasilevsky can we close this issue?

**Comment by nicolevasilevsky** [comment] 2021-09-15 23:08
I think this is confusing because GLAUCOMA, PRIMARY OPEN ANGLE, ADULT-ONSET is an 'included' entry, as is Glaucoma 1, open angle, E. Let's try to check with Chris about this on the Mondo curators call.

**Comment by nicolevasilevsky** [comment] 2021-09-16 17:43
Glaucoma 1, open angle, E should be the primary label

**Comment by kanems** [comment] 2021-12-03 23:37
This decision to use "GLAUCOMA 1, OPEN ANGLE, E" as the primary name for OMIM 137760 seems to run counter to other threads/decisions where Mondo has followed OMIM's preferred name for mapping of MIM numbers and preferred names. If this is, indeed, the final decision and represents an exception rather than the rule for following OMIM naming precedence on Mondo:MIM equivalancies, then GTR/MedGen will follow and put the MONDO ID on the "included" concept rather than the preferred concept (but I will have to review with our team if we will also move the MIM number or keep it on the concept that OMIM asserts is the preferred name.)

**Comment by nicolevasilevsky** [comment] 2021-12-08 00:39
@kanems I don't remember why we decided to go with Glaucoma 1, open angle, E as the primary label, it might be because the p2g relationship box uses that label. I'm actually meeting with Ada tomorrow, so me see if I can get further clarification.

The question is:
is GLAUCOMA, PRIMARY OPEN ANGLE a generic class and should be its own Mondo term and is Glaucoma 1, open angle, E the gene specific class?


![image](https://user-images.githubusercontent.com/6722114/145127722-c190c60a-2a38-4061-8475-88d82207d121.png)

**Comment by kanems** [comment] 2021-12-08 12:24
Thanks @nicole!
We also sent OMIM a message about the p2g tables and mis-matches between the phenotype in the table and the primary title on the OMIM entry, which happens in a subset of OMIM entries. So this is another good example for our message with Ada and Joanna.

**Comment by nicolevasilevsky** [comment] 2021-12-08 18:06
Talking to Ada now - we confirmed GLAUCOMA, PRIMARY OPEN ANGLE is the generic form and Glaucoma 1, open angle, E is the gene associated form. I'll make sure this is properly represented this way in Mondo.

**Closed** 2021-12-23 01:57 UTC
Labels: relabel term, OMIM, question-OMIM
