### ISSUE TITLE
Protege shows false parentage

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#4947] opened 2022-05-19 23:51 UTC
We need to clean up the top level of Mondo. One thing that I cannot figure out is what diseases such as alpha-N-acetylgalactosaminidase deficiency are shown as direct (asserted) children of disease or disorder even though we are not actually asserting this. In any case, this makes it completely confusing for anybody who wants to browse Mondo using Protege. I do not see this using OLS. How can we make Protege stop doing this? @cmungall @matentzn 

![image](https://user-images.githubusercontent.com/4943420/169421995-9c536ad1-74ec-45ce-87bc-eb9b2402eb54.png)

**Comment by pnrobinson** [comment] 2022-05-19 23:55
Using the reasoner and then looking at inferred makes this go away, but it still does not make sense to me...?"

**Comment by matentzn** [comment] 2022-05-20 05:34
This cannot really be changed - you have to run the reasoner. The reason for this behaviour is that the protege hierarchy is generated by what is called a "structural" reasoner. The structural reasoner will see the logical definition, see that it contains "disease or disorder" and place the class under disease or disorder. This is not a bug, its just that the structural reasoner is super stupid.

The axioms are not wrong here (in this case at least) - there are three paths to resolve this ticket:
1. Mondo editors _must_ use the reasoner when browsing the class hierarchy
2. Mondo editors could use mondo.owl (release version) which has the class hierarchy reasoned
3. Logical definitions must be formulated with the most _specific_ genus available, i.e., instead of `disease or disorder and disease caused by disruption of ana activtiy` you say `neurometabolic disease and disease caused by disruption of...` the is redundant, causes a have burden on curation and a proliferation of pattern (or at least the need to curate the "disease" slot in the disruption pattern). 

Up to y'all editors.

**Comment by nicolevasilevsky** [comment] 2022-05-20 20:58
I think we should do #1 or #2.

@pnrobinson is it okay to close this ticket or is there other action needed?

**Comment by nicolevasilevsky** [comment] 2022-05-31 17:36
I will close this but please reopen if further action is needed, thanks!

**Closed by nicolevasilevsky** 2022-05-31 17:36 UTC
Labels: bug
