### ISSUE TITLE
Please add hyphen to Koolen de Vries syndrome term

### ISSUE THREAD

**Issue by tibingaman** [monarch-initiative/mondo#4174] opened 2021-12-16 13:42 UTC
**Mondo term (ID and Label):**
Koolen de Vries syndrome MONDO:0012496

**Suggested new label:**
Koolen-de Vries syndrome

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
ClinGen ID/Autism GCEP

**_Optional_: Any additional information (like supporting evidence, PubMed ID, etc.)**
As with most eponymous disease terms, there should be a hyphen between the authors two last names: (1) Koolen and (2) de Vries

**Comment by kanems** [comment] 2021-12-27 21:41
While names are being considered for this term, I see these are listed as exact synonyms:

> microdeletion 17q21.31 syndrome
> chromosome 17q21.31 deletion syndrome

But is Koolen-de Vries somehow different from MONDO:0018216
**17q21.31 microdeletion syndrome** ?
Orphanet 363958 maps to OMIM: 610443
So should these be merged as a part of the term clean up?

**Comment by nicolevasilevsky** [comment] 2022-01-03 22:30
@sabrinatoro can you take a look at this one.

I agree with @kanems, I think these two are equiv and should be merged:
MONDO_0018216 '17q21.31 microdeletion syndrome'
MONDO_0012496 'Koolen de Vries syndrome'

this would cause a proxy merge with Orphanet. Looks like OMIM has combined these into one term (see [OMIM here](https://omim.org/entry/610443)).

Thanks for your help!

**Comment by nicolevasilevsky** [comment] 2022-01-03 22:32
In the mean time, I relabeled the term per the request above @tibingaman. Thanks for reporting this.

**Comment by sabrinatoro** [comment] 2022-01-04 23:41
@nicolevasilevsky @kanems 
I do not think that MONDO_0018216 '17q21.31 microdeletion syndrome' and MONDO_0012496 'Koolen de Vries syndrome' should be merged. 
Looking at the ontology, there is also "Koolen-de Vries syndrome due to a point mutation" (MONDO:0018217).

According to [here](https://rarediseases.info.nih.gov/diseases/10727/koolen-de-vries-syndrome) and  [here](https://pubmed.ncbi.nlm.nih.gov/20301783)/)
"(Koolen-de Vries syndrome) is caused by mutations in the KANSL1 gene, or by the loss of a small amount of genetic material in chromosome 17 that includes the KANSL1 gene (chromosome 17 q21.31 microdeletion)."

Based on this information, I propose: 
- "Koolen-de Vries syndrome" as a parent term
- 2 children: "Koolen-de Vries syndrome due to 17q21.31 microdeletion", and "Koolen-de Vries syndrome due to a point mutation"

To do: 
- [ ] rename MONDO_0018216 '17q21.31 microdeletion syndrome' to  Koolen-de Vries syndrome due to 17q21.31 microdeletion. 
- [ ] move the following xref from "Koolen-de Vries syndrome" to "Koolen-de Vries syndrome due to 17q21.31 microdeletion": 
UMLS: C1864871, SCTID:717338006, MESH:C566476, DOID:0070076/DOID:0050880


xref that would stay on the parent term: 
GARD:0010727, Orphanet:96169, OMIM:610443 (from omim:A number sign (#) is used with this entry because Koolen-De Vries syndrome can be caused either by heterozygous mutation in the KANSL1 gene (612452) on chromosome 17q21.31 or by a larger deletion of several genes on chromosome 17q21.31.)

xref that I couldn't find (probably obsoleted at the source):
UMLS:CN776874

**Comment by nicolevasilevsky** [comment] 2022-01-11 23:28
sounds good @sabrinatoro, thanks!

**Closed** 2022-01-13 17:16 UTC
Labels: Ordo-xref, relabel term, merge
