### ISSUE TITLE
[Merge] MONDO:0009453 'immune deficiency disease'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#6499] opened 2023-07-26 01:52 UTC
**Mondo term (ID and Label)**
MONDO:0009453 'immune deficiency disease'

**Reason for deprecation**
@sabrinatoro can you please review this?

The term above is equiv to this OMIM class: https://omim.org/entry/242850

whereas the term below is equiv to an OMIMPS:
https://www.omim.org/phenotypicSeries/PS300755,PS601495

Maybe it it just best to obsolete the term above? Or rename it? It's very confusing. Or maybe the OMIM term should be the non-heriditary form? It doesn't mention inheritance in the description.

We have [acquired immunodeficiency](http://purl.obolibrary.org/obo/MONDO_0017769) and two inherited classes (those mentioned here) and maybe we need a grouping triad?

**Term to be merged with**
MONDO:0021094 'immunodeficiency disease'

**Comment by sabrinatoro** [comment] 2023-07-27 15:54
@nicolevasilevsky 
Here is what I have found: 
- MONDO:0009453 'immune deficiency disease': [OMIM:242850](https://omim.org/entry/242850) is a VERY old record (1973, reviewed last 2009). And the MESH id refers to this OMIMid. 
I don't know enough about immunodeficiency, but the record suspects IgM deficiency. 
So, I would obsolete this term based on historical reasons. 

The questions now are: 
1) Is this term the same as "immunodeficiency disease" (and ie should be merged)?
I cannot tell that these terms report to the same concept. I don't think for sure (the description in OMIM:242850 seems to describe a disease that is an immunodeficiency disease, but is more specific than the general "immunodeficiency disease". **So I personally would lean towards obsoleting MONDO:0009453 instead of merging it.** 

2) What should we do with the children of MONDO:0009453?
Based on [here](https://www.ncbi.nlm.nih.gov/books/NBK500027): immunodeficiency (MONDO:0021094) : 
- results from a failure or absence of elements of the immune system, including lymphocytes, phagocytes, and the complement system. 
- have 2 "main" types: 
       - primary immunodeficiency = inborn errors of immunity (MONDO:0003778) 
             - hereditary, caused by genetic mutation that affect the immune system
             - subdivided into types: T-cell deficiency, B-cell deficiency, both T-cell and B-cell deficiency, complement deficiency, phagocyte deficiency, Immunoglobulin A deficiency.
             - [publication](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9244088)
       - secondary immunodeficiency = acquired immunodeficiency (I think)
             - caused by steroid, obesity, AIDS,...
 **Therefore, I think the children of the current MONDO:0009453 can be moved to "MONDO:0021094 'immunodeficiency disease'**"

**Comment by sabrinatoro** [comment] 2023-08-24 00:12
Question: 
is there a difference between "immune deficiency disease" and "immunodeficiency disease"?

**Comment by sabrinatoro** [comment] 2024-03-22 16:55
closing in favor of https://github.com/monarch-initiative/mondo/issues/7461

**Closed by sabrinatoro** 2024-03-22 16:55 UTC
Labels: merge, Ada/Peter
