### ISSUE TITLE
[Revise subclass] radiation or chemically induced disorder

### ISSUE THREAD

**Issue by zoependlington** [monarch-initiative/mondo#922] opened 2019-11-04 10:26 UTC
**Mondo term (ID and Label)**
MONDO:0045028 (radiation or chemically induced disorder)

**Suggested revision and reasons**
During our recent remodelling of top level EFO disease terms, we have been asked to move this term to be a child of injury rather than as a child of disease. As it is a Mondo term, we can not move it and so bringing the discussion/request here. See https://github.com/EBISPOT/efo/issues/585.

**Comment by cmungall** [comment] 2019-11-05 00:21
Overall this makes sense, this is a good time to do some cleanup first

here is the hierarchy:

![rad](https://user-images.githubusercontent.com/50745/68168788-db02b400-ff1e-11e9-9c63-8ddcfec4d197.png)

we already have 'radiation injury', this would be merged?

I think disease and injury should be disjoint, but as can be seen there is lots of cross-over at the moment

**Comment by zoependlington** [comment] 2019-11-06 11:00
Tagging @smnorthen @paolaroncaglia @d0choa so they can join the discussion.

I think merging radiation or chemically induced disorder with radiation injury (perhaps renaming incorporate the chemical aspect too? Or having an equivalent chemical injury term?) sounds logical. We have quite an overlap of disease and injury in EFO so it would also be nice to clean up in alignment with Mondo, too.

**Comment by smnorthen** [comment] 2019-11-06 14:08
@zoependlington
I think merging the two would be fine, but the radiation injury parent name should be changed to include the chemical aspect too.

**Comment by paolaroncaglia** [comment] 2019-11-07 10:13
@cmungall 
@zoependlington 
@smnorthen 
@d0choa
I do not oppose making ‘radiation or chemically induced disorder’ a subclass of ‘injury’ rather than disease. However, I’d suggest to revise the definition of ‘injury’ to better accommodate its new descendants. Currently it reads “Damage inflicted on the body as the direct or indirect result of an external force, with or without disruption of structural continuity.” The wording “external force” does not apply well to chemicals and should be expanded or changed. I’m also thinking about 
cancers that are induced by radiation, or by exposure to some chemicals (e.g. mesotheliomas due to asbestos). One would classify a cancer based on its type and location rather than its (often uncertain) cause, but in cases where the origin could be clearly traced to radiation or chemicals, the curation (rather than ontology placement) of that cancer to a term that is a descendant of ‘injury’ would be less problematic if injury were defined more broadly. For the same reason, I’m afraid that making injury and disease disjoints may cause plenty of unwanted trouble. :-)

**Comment by cmungall** [comment] 2019-11-12 01:53
I'd like to push and see if we could make injury and disease disjoint. For the cancer case, there would be some kind of non-isa causal relation back to the source injury.

In fact I wonder if the whole injury branch should not eventually move to ECTO cc @diatomsRcool

**Comment by nicolevasilevsky** [comment] 2019-12-17 15:38
@cmungall do you still want to consider making injury and disease disjoint? Or should we make the  definition of 'injury' more broad in Mondo (per @paolaroncaglia's suggestion)?

**Comment by zoependlington** [comment] 2019-12-17 15:40
Right now Open Targets have the therapeutic area of "injury, poisoning and other complication" which sits directly under disease. Making injury and disease disjoint would therefore be quite damaging to this and the way we have modelled our Open Targets profile.

**Comment by cmungall** [comment] 2019-12-17 18:53
we don't want to injure opentargets...

I think it would be good to plan some long term improvements to this area. And I also think we should try and not mix the two hierarchies where possible.

More generally: We should encode any axioms that OT/EBI needs in the ontology via axiom annotations. We can say an is-a is sourced from OT, and add something to curator guide that states these should not be changed without consultation

**Comment by d0choa** [comment] 2019-12-17 20:41
Just for the record, the logic behind having such term under disease is that it would make sense from a clinical perspective to group all diseases caused by external agents, similar to what Meddra group in their SOC Injury, poisoning and procedural complications.  

We don’t want to become blockers of any future improvements in the ontology, so we’ll try to help on easing the changes if any strategy is agreed.

**Comment by zoependlington** [comment] 2020-01-16 18:14
From the EFO side, we can produce a list of axioms required for EFO/OT so any plan to change them in Mondo will be flagged for us.

**Comment by nicolevasilevsky** [comment] 2021-09-29 15:41
this term has been obsoleted, I think this ticket can be closed, please reopen if any other action is needed

**Closed by nicolevasilevsky** 2021-09-29 15:41 UTC
Labels: Revise subclass, EFO
