### ISSUE TITLE
Consider changing mental retardation to intellectual disability

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#34] opened 2017-12-05 17:30 UTC
This would be consistent with GARD
https://github.com/obophenotype/human-phenotype-ontology/issues/3290

**Comment by nicolevasilevsky** [comment] 2017-12-05 17:41
This sounds good to me. I think coordinating with OMIM and Orphanet is a good idea too.

**Comment by cmungall** [comment] 2017-12-09 02:52
is there a preferred term re hearing loss vs deafness where the hearing loss is incomoplete, e.g autosomal dominant nonsyndromic deafness. GHR uses hearing loss which seems preferable http://ghr.nlm.nih.gov/condition/nonsyndromic-deafness

**Comment by cmungall** [comment] 2017-12-09 03:57
What about where the MR is embedded inside a syndromic label? E.g. ectodermal dysplasia with mental retardation and syndactyly

**Comment by cmungall** [comment] 2017-12-09 03:58
This will impact 2 terms in protected subsets

```
[Term]
id: MONDO:0010955
name: ectodermal dysplasia with mental retardation and syndactyly
subset: clingen
synonym: "ECTODERMAL DYSPLASIA WITH MENTAL RETARDATION AND SYNDACTYLY" RELATED [OMIM:600906]
xref: MESH:C538018 {source="MONDO:equivalentTo", source="MONDO:ontobio"}
xref: OMIM:600906 {source="MONDO:equivalentTo", source="MONDO:Leader"}
xref: UMLS:C1833169 {source="NCBI:mim2gene_medline", source="OMIM:600906"}
is_a: MONDO:0003847 ! inherited genetic disease

[Term]
id: MONDO:0014911
name: growth retardation, intellectual developmental disorder, hypotonia, and hepatopathy; GRIDHH
subset: clingen
synonym: "GRIDHH" EXACT [OMIM:617093]
synonym: "Growth Retardation, Intellectual Developmental Disorder, Hypotonia, and Hepatopathy" EXACT [OMIM:617093]
xref: OMIM:617093 {source="MONDO:equivalentTo", source="MONDO:Leader"}
xref: UMLS:C4310720 {source="NCBI:mim2gene_medline"}
is_a: MONDO:0003847 ! inherited genetic disease
```

**Comment by cmungall** [comment] 2017-12-09 04:02
Proposed implementation date: Jan 5, pending discussion

**Comment by nicolevasilevsky** [comment] 2020-03-10 19:54
note to self - check to see if this was done/can be closed

**Comment by nicolevasilevsky** [comment] 2020-03-25 00:07
This wasn't done, there are still a lot of terms with MR in the label.

**Comment by nicolevasilevsky** [comment] 2020-12-10 01:46
duplicate of #2310.

Reassigning to Nico.

**Closed** 2020-12-11 18:46 UTC
Labels: high priority
