### ISSUE TITLE
make sure there is documentation on the difference b/w proxy merge and reverse proxy merge

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#4545] opened 2022-02-25 23:17 UTC
and what is allowed, what isn't

maybe there is documentation already, need to check

**Comment by matentzn** [comment] 2022-03-05 11:53
A proxy merge is caused by two equivalentTo mappings two the same external ID:

MONDO:123 skos:exactMatch OMIM:123
MONDO:124 skos:exactMatch OMIM:123

The name proxy merge comes from the fact that MONDO:123 and MONDO:124 are merged "by proxy". This case is strictly forbidden in Mondo and we have QC guarding against it.

What I started calling "reverse proxy merges" is not really a thing according to @cmungall definitions. It happens when two external concepts are considered the same by Mondo, for example:

```
MONDO:124 skos:exactMatch OMIM:123
MONDO:124 skos:exactMatch OMIM:124
```

In this case, OMIM:123 and OMIM:124 are merged together into one MONDO id. This case is totally allowed, but it does suggest a bug in the upstream sources. In my opinion, we do not do enough review of these cases, and we should probably have our current "reverse proxy merges" reviewed by some medical terminology experts.

**Closed** 2022-03-25 17:57 UTC
Labels: documentation
