### ISSUE TITLE
Merge MONDO_0019510 'autosomal dominant medullary cystic kidney disease without hyperuricemia' is equivalent to MONDO_0020726 'medullary cystic kidney disease 1'.

### ISSUE THREAD

**Issue by tsneddon** [monarch-initiative/mondo#1878] opened 2020-08-11 18:40 UTC
The ClinGen Kidney Disease CDWG would like to request a merge of MONDO:0019510 and MONDO:0008264 as they are both caused by variants in the _MUC1_ gene.
Please retain the 'ADTKD-MUC1' synonym.
Ideally we would like to rename the entry, or at least add as an alias, the term 'autosomal dominant tubulointerstitial kidney disease due to mutations in MUC1 (ADTKD-MUC1)'
PMID:25738250
Thanks,
Tam

**Comment by nicolevasilevsky** [comment] 2020-09-22 05:19
Hi @tsneddon 

I added the synonyms 'autosomal dominant tubulointerstitial kidney disease due to mutations in MUC1' and  'ADTKD-MUC1' to MONDO:0008264 'autosomal dominant medullary cystic kidney disease with or without hyperuricemia'.

I'm not sure about merging the two terms because both classes are still available in Orphanet, and we want to keep in alignment with Orphanet.

If we were to merge these two classes, we'd want to coordinate with Orphanet first and see if they want to merge the two classes, or if they still consider them to do be two valid classes.

Would you like me to try to coordinate with them? Or is adding the synonyms sufficient? They will be available in the next release at the end of Sept/early Oct.

**Comment by nicolevasilevsky** [comment] 2020-10-01 02:04
pinging @tsneddon

**Comment by tsneddon** [comment] 2020-10-02 00:35
@nicolevasilevsky - OK, no need to merge. I'm not sure what the new MONDO version looks like but now I see that MONDO:0008264 (autosomal dominant medullary cystic kidney disease with or without hyperuricemia) has the definition "An inherited form of cystic kidney disease that leads to fibrosis and impaired renal function as a result of defects in the MUC1 gene, which encodes mucin 1" but has children that include MONDO:0019511 (UMOD) and MONDO:0019510 (MUC1). Perhaps the definition of MONDO:0008264 needs to be changed?

**Comment by nicolevasilevsky** [comment] 2020-10-08 00:51
Hi @tsneddon 

Would you like me to extend the text def to something like:

**Comment by nicolevasilevsky** [comment] 2020-10-12 23:41
pinging @tsneddon

**Comment by tsneddon** [comment] 2020-10-13 00:18
@nicolevasilevsky - I think the main issue is that MONDO:0019510 (MUC1-related autosomal dominant tubulointerstitial kidney disease) is a child of MONDO:0008264 (autosomal dominant tubulointerstitial kidney disease due to mutations in MUC1). Is this logical?

**Comment by nicolevasilevsky** [comment] 2020-10-13 22:19
@tsneddon thanks so much - I see the problem, I am working on this now.

**Comment by nicolevasilevsky** [comment] 2020-10-13 23:47
This one is complicated, it turns out! 

I believe MONDO_0019510 'autosomal dominant medullary cystic kidney disease without hyperuricemia' is equivalent to MONDO_0020726 'medullary cystic kidney disease 1'.

I am going to merge these two. I'll need @cmungall to review before this can be merged into the ontology though.

I also did the following. @tsneddon let me know if anything needs clarification.

Upon reviewing these two classes, I have done the following:

MONDO_0008264 'autosomal dominant medullary cystic kidney disease with or without hyperuricemia'

Revise def:
"A group of genetic kidney diseases that cause progressive loss of kidney function caused by mutations in the genes encoding uromodulin (UMOD), hepatocyte nuclear factor-1β (HNF1B), renin (REN), and mucin-1 (MUC1)." [GARD:0010801, PMID:25738250]

add subclassOf relationships:
disease_has_basis_in_dysfunction_of http://identifiers.org/hgnc/11630 {source="PMID:25738250"} ! HNF1B
disease_has_basis_in_dysfunction_of http://identifiers.org/hgnc/12559 {source="GARD:0010801", source="PMID:25738250"} ! UMOD
disease_has_basis_in_dysfunction_of http://identifiers.org/hgnc/7508 {source="GARD:0010801", source="PMID:25738250"} ! MUC1
disease_has_basis_in_dysfunction_of http://identifiers.org/hgnc/9958 {source="GARD:0010801", source="PMID:25738250"} ! REN

MONDO_0019510 'autosomal dominant medullary cystic kidney disease without hyperuricemia'

Add def: 
 "An inherited disorder that causes a gradual loss of kidney function, caused by a mutation in the MUC1 gene that leads to production of an abnormal mucin 1 protein, which deposits in the kidney and leads to slow loss of kidney function." [GARD:0007002]

 add subclassOf relationship:
 'disease has basis in dysfunction of' some MUC1

Moved synonyms from parent class to this class:
"ADTKD-MUC1" EXACT [Orphanet:88949, PMID:25738250]
"autosomal dominant tubulointerstitial kidney disease due to mutations in MUC1" EXACT [PMID:25738250]

MONDO_0019511 'autosomal dominant medullary cystic kidney disease with hyperuricemia'
Add def:
"An inherited disorder that causes a gradual loss of kidney function that eventually leads to the need for kidney transplantation or dialysis between the ages of 30 and 70,. which is caused by a mutation in the UMOD gene, which leads to the build-up of the altered uromodulin protein in the tubules of the kidney, leading to slow loss of kidney function. Patients with ADTKD-UMOD have high blood levels of uric acid before kidney failure develops, and some affected individuals may develop gout." [GARD:0010679]

 add subclassOf relationship:
 disease_has_basis_in_dysfunction_of http://identifiers.org/hgnc/12559 {source="GARD:0010679"} ! UMOD

MONDO_0020726 'medullary cystic kidney disease 1'
 Remove equiv axiom

**Comment by nicolevasilevsky** [comment] 2020-10-13 23:48
Note - I revised the title

**Comment by maglott** [comment] 2020-10-14 20:55
should the list of genes in the definition be OR rather than AND
something more like
...caused by mutations in genes encoding uromodulin (UMOD), hepatocyte nuclear factor-1β (HNF1B), renin (REN), or mucin-1 ...

**Comment by galyea-gard** [comment] 2020-10-15 19:31
Hi!  Very interesting all of these.  In GARD we have the following: 
Autosomal dominant tubulointerstitial kidney disease (parent term) that have the following subtypes: 

- Autosomal dominant tubulointerstitial kidney disease due to MUC1 mutations (synonyms: MCKD1; **Medullary cystic kidney disease type 1**(which comes from OMIM); MUC1-related autosomal dominant medullary cystic kidney disease; MUCI-related ADTKD; MUC1-related autosomal dominant tubulointerstitial kidney disease; Medullary cystic kidney disease 1 (former); Mucin-1 kidney disease; ADTKD due to MUC1 mutations; ADTKD-MUC1; Autosomal dominant tubulointerstitial kidney disease, MUC1-associated.

- Autosomal dominant tubulointerstitial kidney disease due to REN mutations (synonyms:  FJHN type 2; REN-associated familial juvenile hyperuricemic nephropathy; REN-associated kidney disease; Familial juvenile hyperuricemic nephropathy type 2; REN-associated kidney disease); ADTKD-REN; REN-associated FJHN; Hyperuricemic nephropathy, familial juvenile 2; ADTKD due to REN mutations; Autosomal dominant tubulointerstitial kidney disease, REN-related)

- Autosomal dominant tubulointerstitial kidney disease due to UMOD mutations (synonyms: ADTKD-UMOD; Autosomal dominant medullary cystic kidney disease type 2 (former); UMOD-related ADTKD; Autosomal dominant medullary cystic kidney disease type 2; MCKD2; UMOD-related autosomal dominant tubulointerstitial kidney disease; Familial juvenile hyperuricemic nephropathy type 1; Medullary cystic kidney disease 2 (former); Familial Juvenile Hyperuricemic Nephropathy 1; UMOD-Associated Kidney Disease; Autosomal Dominant Tubulointerstitial Kidney Disease, UMOD-Related; Uromodulin kidney disease; Uromodulin-associated kidney disease; ADTKD due to UMOD mutations)

We decided the preferred terms and synonyms by reviewing the newer and more relevant literature.  Orphanet is outdated but there are GeneReviews. 

Thank you, Gioconda

**Comment by tsneddon** [comment] 2020-10-16 18:49
@galyea-gard - it sounds like GARD is in agreement with the preferred nomenclature of the ClinGen Cystic & Ciliopathy GCEP for these genes ie ADTKD-GeneSym, thanks!

**Comment by nicolevasilevsky** [comment] 2020-10-16 19:22
@maglott 
>should the list of genes in the definition be OR rather than AND
something more like
...caused by mutations in genes encoding uromodulin (UMOD), hepatocyte nuclear factor-1β (HNF1B), renin (REN), or mucin-1

Yes! I fixed that

**Comment by nicolevasilevsky** [comment] 2020-10-16 19:41
To do:
- [ ] need to add `Autosomal dominant tubulointerstitial kidney disease due to REN mutations` - we don't have this term from GARD: https://rarediseases.info.nih.gov/diseases/13461/autosomal-dominant-tubulointerstitial-kidney-disease-due-to-ren-mutations
- [ ] merge:

MONDO_0019511 | autosomal dominant medullary cystic kidney disease with hyperuricemia' | MONDO_0011379 | medullary cystic kidney disease 2'
-- | -- | -- | --

owltools mondo-edit.obo  --obsolete-replace MONDO:0019511 MONDO:0011379 -o -f obo mondo-edit.obo

**Justification:**
Orphanet obsoleted `Orphanet:209886 Familial juvenile hyperuricemic nephropathy type 1`, (`MONDO_0008073 'familial juvenile hyperuricemic nephropathy type 1'`)

**Closed** 2020-10-16 20:20 UTC
Labels: ClinGen, definition, merge
