### ISSUE TITLE
Hypersensitivity pneumonitis

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#1821] opened 2020-07-26 14:47 UTC
Please see this detailed comment with suggestions for disease entities and PMIDs

https://github.com/obophenotype/human-phenotype-ontology/issues/5806

**Comment by nicolevasilevsky** [comment] 2020-08-13 01:14
this is a duplicate of #1639

I am going to close this here.

**Closed by nicolevasilevsky** 2020-08-13 01:14 UTC
Labels: New term request, duplicate, high priority
