### ISSUE TITLE
MONDO:0005046 'immune system disease' has exact synonym 'immune system disease'

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#749] opened 2019-06-26 10:49 UTC
Hi,
MONDO:0005046 'immune system disease' has an exact synonym that is the same as the term label, i.e. 'immune system disease'. EFO inherited it from MONDO (we didn't have it in EFO2). I noticed it as I started a review of synonyms of high-level terms that are of interest for some of our users. This was the first term I looked at :-) so I wonder - does MONDO not have a check to avoid exact synonyms that are identical to labels (i.e. label of the term itself as well as any other term in the ontology), as we had in GO? If yes, I must have stumbled on a singularity. If not, would you consider implementing such a check?
Thanks!

**Comment by paolaroncaglia** [comment] 2019-06-26 10:49
Tagging @zoependlington and @simonjupp for their information.

**Comment by nicolevasilevsky** [comment] 2019-06-27 00:54
@cmungall or @ShahimEssaid can address this. 

I would think there would already be an existing check for this.

@cmungall should we remove the synonym that is a duplicate of the label? The dbxef is MONDO:patterns/location

**Comment by paolaroncaglia** [comment] 2019-06-27 12:26
@nicolevasilevsky @ShahimEssaid @cmungall 
Thanks for looking into this.

**Comment by paolaroncaglia** [comment] 2019-08-20 14:53
Hi @nicolevasilevsky @ShahimEssaid @cmungall,
Any update on this issue, please? I see it's still in MONDO (and in EFO as we get it from MONDO :-) ).
Thanks!

**Comment by nicolevasilevsky** [comment] 2019-08-20 16:42
@paolaroncaglia I created a PR to remove the duplicate synonym.

@cmungall will have to let you know about the checks for this.

**Comment by paolaroncaglia** [comment] 2019-08-21 12:40
Thanks @nicolevasilevsky !

**Comment by paolaroncaglia** [comment] 2019-09-24 13:06
@nicolevasilevsky 
@cmungall 
This issue seems fixed in Mondo now, feel free to close if so. Thanks.

**Closed** 2019-09-24 15:21 UTC
Labels: EFO, bug, pending PR
