### ISSUE TITLE
need check - no hierarchical relation between gene-level diseases in MONDO

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#1532] opened 2020-05-19 05:33 UTC
need a way of checking that there are no hierarchical relation between gene-level diseases in Mondo

related to https://github.com/monarch-initiative/mondo/issues/745

**Comment by nicolevasilevsky** [comment] 2020-12-10 19:33
see report
https://github.com/monarch-initiative/mondo/blob/master/src/ontology/reports/mondo_analysis.md#check-no-subclass-between-genetic-disease-warning

**Comment by nicolevasilevsky** [comment] 2020-12-10 23:15
This came up on the QC check:
'congenital fiber-type disproportion myopathy' subclass of actinopathy

actinopathy: 'disease has basis in dysfunction of' some ACTA1

'congenital fiber-type disproportion myopathy' has mutations in several genes, including ACTA1

@matentzn is there a way to relax this check so this is acceptable?

**Comment by matentzn** [comment] 2020-12-10 23:29
Are we sure that the genetic disease pattern with multiple genes is correct? Isn't there an implicit "and has basis in dysfunction of only ATC" that is simply being closed by the definition definition? This needs the be run by @cmungall. I kind of would assume that "has basis in dysfunction of" implies an exhautive enumeration..

**Comment by nicolevasilevsky** [comment] 2020-12-10 23:34
Good question @matentzn. I'll send Chris a message on Slack.

There is one more example here - same thing as above: MONDO:0009711  congenital fiber-type disproportion myopathy, child of actinopathy

**Comment by nicolevasilevsky** [comment] 2020-12-10 23:38
Note to self - these all should have been addressed on PR #2440 except

term | term_label | d2 | d2_label 
-- | -- | -- | --
MONDO:0009711 | congenital fiber-type disproportion myopathy | MONDO:0100084 | actinopathy
MONDO:0009711 | congenital fiber-type disproportion myopathy | MONDO:0100084 | actinopathy

**Comment by cmungall** [comment] 2020-12-10 23:54
See comments in #900 - rename MONDO:0100084 to alpha-actinopathy (there is a good argument to obsoleted and create a new). I'm wondering where it came from, looks like an orphanet term...

**Comment by cmungall** [comment] 2020-12-10 23:56
"'congenital fiber-type disproportion myopathy' subclass of actinopathy"

the check is doing it's work as there are multiple things wrong here

name: congenital fiber-type disproportion myopathy
def: "A rare genetic disorder caused by mutations in the TPM3, ACTA1, RYR1 and SEPN1 genes. It is inherited in an autosomal dominant or recessive pattern and rarely in an X-linked pattern. It manifests with myopathy throughout the body, particularly in the muscles of the shoulders, upper arms, hips, and thighs. Affected individuals may have contractures, lordosis, or scoliosis. In a minority of cases mild to severe breathing problems may occur." [NCIT:C120046]

the def says OR, but the current parents says it's necessarily ACTA1!

Note the axioms for this class have a conjunction of causes. This should only be the case for polygenic diseases! Multiple axioms in OWL means AND not OR!

**Comment by nicolevasilevsky** [comment] 2020-12-11 01:01
@cmungall the definition says AND:
"...disorder caused by mutations in the TPM3, ACTA1, RYR1 **and** SEPN1 genes."

Also, it is a child of other single gene terms:
'RYR1-related myopathy'
'TPM2-related myopathy'
'TPM3-related myopathy'

these didn't come up as an error though.

I am more confused now!

**Comment by nicolevasilevsky** [comment] 2020-12-11 01:50
For the record, Chris clarified for me - this is not a polygenic disease, the def is meant to imply 'or', not 'and'. I removed the gene annotations and the gene-related parents.

**Closed** 2020-12-11 15:43 UTC
Labels: QC, tech
