### ISSUE TITLE
split term: oculoectodermal syndrome AND oculoectodermal syndrome, somatic

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#6722] opened 2023-09-28 20:11 UTC
**oculoectodermal syndrome AND oculoectodermal syndrome, somatic:**  MONDO:0010854
I don't really know what should be done in this case but I am confused about why these seemingly contradictory terms (or at least parent/subcategory) are both exact synonyms to Toriello-Lacassie-Droste syndrome.  

Is this a subcategory of treatment of titles of OMIM's allelic variants (or genemap terms)?

**Comment by nicolevasilevsky** [comment] 2023-10-13 15:23
Hi @maglott, nice to hear from you 😄 . We are focused on a [mass obsoletion](https://github.com/monarch-initiative/mondo/issues?q=is%3Aissue+is%3Aopen+label%3A%22mass+obsoletion%22) effort this month, and will look at this more closely in November or later. We appreciate your patience.

**Comment by nicolevasilevsky** [comment] 2023-11-21 00:11
@ahamosh, can you give us your advice on this?

Is [OMIM:600268](https://omim.org/entry/600268) equivalent to [Orphanet Toriello-Lacassie-Droste syndrome](https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert=3339)?

The OMIM record says there is "evidence that oculoectodermal syndrome (OES) is caused by somatic mosaicism for mutations in the KRAS gene ([190070](https://omim.org/entry/190070)) on chromosome 12p12.". But at the end, it says "[Toriello et al. (1993)](https://omim.org/entry/600268#14) concluded that a new dominant mutation is possible in this disorder, but autosomal recessive inheritance could not be excluded."

Currently, oculoectodermal syndrome, somatic is an exact synonym. @maglott is asking if this should be split into a new class or if not, I wonder if maybe this should be a related synonym?

Thank you!

**Comment by ahamosh** [comment] 2023-11-21 04:23
Based on the OMIM entry,  oculoectodermal syndrome is caused by somatic mutations in the KRAS gene.  I don't think that this can be dominant or recessive.  I think that the comment relates to musings of Dr. Toriello in 1993.  As to whether this is an exact match to what is in Orphanet, I would say that the Orphanet entry Toriello-Lacassie-Droste syndrome has an erroneous inheritance.  From KRAS, it says somatic mutations cause this disease.

**Comment by nicolevasilevsky** [comment] 2023-11-21 15:03
Thanks @ahamosh. I'll let Orphanet know.

@maglott, I think it is okay to leave these two terms lumped together. I'll close this ticket but please let me now if you have further questions or feel free to reopen.

Thanks!

**Closed by nicolevasilevsky** 2023-11-21 15:03 UTC
Labels: split, Ada/Peter
