### ISSUE TITLE
Please check top hierarchy in MONDO

### ISSUE THREAD

**Issue by paolaroncaglia** [monarch-initiative/mondo#726] opened 2019-06-07 13:16 UTC
Hi,

There may be an issue with some of the top terms in the most recent MONDO release. This is what we see in OLS:

![image](https://user-images.githubusercontent.com/4982516/59106584-0e70f080-8937-11e9-95a0-55b26d4c1139.png)

Thanks for checking.

**Comment by paolaroncaglia** [comment] 2019-07-03 09:57
Hi @cmungall and @nicolevasilevsky (cc @zoependlington ),
Following up on this ticket:
We updated the MONDO version in OLS with your most recent release, but we still see the same top classes as above and they look a bit weird. Ontobee hasn't loaded your latest release yet (and we can't easily load MONDO in Protege), so we can't double-check if it is due to an OLS issue by any chance, or if it's indeed a MONDO issue. If you could please take a look from your side that'd be great, thanks.

**Comment by nicolevasilevsky** [comment] 2019-07-03 23:21
The two MONDO terms are obsoleted. The NCBI taxon terms appear to be properly hanging out in the hierarchy where they should be.

**Comment by paolaroncaglia** [comment] 2019-07-04 11:05
@nicolevasilevsky (cc @zoependlington )
Thanks for your feedback. We won't worry about the NCBI taxon terms then. As for the two MONDO terms, if they're obsoleted, I wouldn't expect them to sit at the top of the hierarchy, and I'd expect them to be prefixed with "obsolete". I'm slightly confused. If they look ok from the MONDO side, it could be an OLS issue, but other obsolete MONDO terms look fine to me.

**Comment by nicolevasilevsky** [comment] 2019-07-08 18:09
This terms don't have labels, apparently:
![image](https://user-images.githubusercontent.com/6722114/60832454-c11fb300-a170-11e9-8bd5-45c38aeda6bd.png)

@cmungall could you help investigate? I am not sure what the issue is.

**Comment by paolaroncaglia** [comment] 2019-11-21 17:55
@nicolevasilevsky 
@cmungall 
We're still seeing MONDO:0001201 at the top of the hierarchy in https://www.ebi.ac.uk/ols/ontologies/mondo (see https://github.com/monarch-initiative/mondo/issues/726#issue-453508596). The other Mondo term, instead, has gone (see https://github.com/monarch-initiative/mondo/issues/726#issuecomment-509332877). Is it possible that you fixed the latter but forgot the former? :-)

**Comment by nicolevasilevsky** [comment] 2019-11-21 18:03
I don't know what the fix is for this, both of those terms appear the same way in the hierarchy to me in Protege.

@cmungall could you help?

Thanks!

**Comment by cmungall** [comment] 2019-11-25 18:50
You should be able to diagnose this using the usage tab in Protege

there is an annotation that references the obsolete class:

```
id: MONDO:0001202
name: prostatic cyst
synonym: "cyst of prostate" EXACT [DOID:11133, ICD9CM_2006:600.3]
xref: COHD:201617 {source="MONDO:equivalentTo"}
xref: DOID:11133 {source="MONDO:equivalentTo"}
xref: ICD10:N42.83 {source="MONDO:equivalentTo", source="DOID:11133"}
xref: ICD9:599.89 {source="MONDO:relatedTo", source="i2s"}
xref: ICD9:600.3 {source="MONDO:equivalentTo", source="i2s", source="DOID:11133"}
xref: SCTID:409658007 {source="MONDO:equivalentTo", source="DOID:11133", source="MONDO:kboom-pr-1.00/0.91/29.66"}
xref: UMLS:C1443972 {source="MONDO:equivalentTo", source="DOID:11133"}
is_a: MONDO:0003105 {source="DOID:11133/inferred", source="linkedlifedata"} ! prostate disease
relationship: excluded_subClassOf MONDO:0001201 {source="DOID:11133"}
```

just remove the excluded_subClassOf annotation

**Comment by cmungall** [comment] 2019-11-25 18:57
But note it's not actually wrong to have an annotation point at a deprecated class by OBO policy

However, I can see that it would be confusing for annotations between IRIs, so we should probably have a check to prohibit these

But I think part of the confusion is with OLS. I think OLS is treating these annotations as object assertions and that is inducing the alt_id to become visible in an odd way. Contrast with other merged classes (ie alt_ids)

http://purl.obolibrary.org/obo/MONDO_0021215

does not even show up in OLS

May want to make an OLS ticket here

**Closed** 2019-11-26 02:13 UTC
Labels: EFO, bug, pending PR

**Comment by paolaroncaglia** [comment] 2019-11-26 11:48
@cmungall 
@nicolevasilevsky 
Please see
https://github.com/EBISPOT/OLS/issues/302#issuecomment-558593765
