### ISSUE TITLE
[Merge] MONDO:0000212 AND MONDO:0007749

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#2926] opened 2021-04-14 12:20 UTC
**Mondo term (ID and Label)**
autosomal recessive infantile hypercalcemia/MONDO:0007749 and 

hypercalcemia, infantile/MONDO:0000212

**Reason for deprecation**
Clearly AR should be a child of _hypercalcemia, infantile_ if both are to be retained, but NCBI had equated the concepts represented by https://www.omim.org/phenotypicSeries/PS143880
and https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=300547 because both have the same children.  NCBI can split if there is a need to retain both terms, but at present, PS143880 and ORHPA:300547  seem to represent the same class.  

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment] 2021-05-03 16:57
@ahamosh do you think these two should be merged?

MONDO:0007749	autosomal recessive infantile hypercalcemia and
MONDO:0000212 hypercalcemia, infantile (equiv to [Hypercalcemia, infantile](https://www.omim.org/phenotypicSeries/PS143880))

Right now, Orphanet has Orphanet:300547 Autosomal recessive infantile hypercalcemia equiv to [HYPERCALCEMIA, INFANTILE, 1; HCINF1](https://omim.org/entry/143880)

**Comment by nicolevasilevsky** [comment] 2021-05-03 17:02
@maglott I think maybe the merger should be:
MONDO_0007749 'autosomal recessive infantile hypercalcemia' (Orphanet:300547) - _obsolete this and replace with_
MONDO_0020739 'autosomal recessive infantile hypercalcemia 1' (OMIM:143880)

**Comment by maglott** [comment] 2021-05-03 17:58
@nicolevasilevsky , where will Orphanet:300547 go?  It is not autosomal recessive infantile hypercalcemia 1.
For tracking purposes, if MONDO_0007749 is 'replaced with' MONDO_0020739, does that indicate they are equivalent? 
To me that is misleading.

**Comment by nicolevasilevsky** [comment] 2021-05-03 21:38
Hi @maglott - my bad, I thought Orphanet:300547 was equivalent to MONDO_0020739 'autosomal recessive infantile hypercalcemia 1', but it sounds like it is not?

Orphanet has an equivalence mapping between Orphanet:300547 and OMIM:143880 HYPERCALCEMIA, INFANTILE, 1, which is equivalent to MONDO_0020739 'autosomal recessive infantile hypercalcemia 1'.

I just wonder if Orphanet:300547 Autosomal recessive infantile hypercalcemia is equivalent to the more generic grouping class (MONDO:0000212 hypercalcemia, infantile (equiv to OMIMPS:143880 Hypercalcemia, infantile). Right now, the two terms in the PS are autosomal recessive, but if OMIM added other terms to that PS that were not AR, then that would not work. Not sure if that is something that might happen, I hope @ahamosh can comment.

Thanks for clarifying, @maglott!

**Comment by sabrinatoro** [comment] 2021-07-07 17:51
Hello @maglott 
I'm Sabrina, a new curator who recently joined the Mondo team.
We will address your issue as soon as possible. Thank you for your patience.
If this is a high priority, please let me know and we can prioritize it. Thank you!

**Comment by ahamosh** [comment] 2021-10-06 22:29
as far as I can tell orphanet:300547 is the same as the OMIMPS:143880, not just OMIM 143880.

**Comment by kanems** [comment] 2022-03-08 13:28
Hi all, So I know this merge was a long-time coming and based on the cross-references I would agree that the terms, as _currently_ X-ref'ed, are the same. I have a concern that in the long-run we may need to split these concepts back out if/when a form of infantile hypercalcemia that is any inheritance OTHER than autosomal recessive is discovered and gets lumped under this concept. And even now the exact synonyms and X-refs are a bit confusing: Both "autosomal recessive infantile hypercalcemia" and "idiopathic infantile hypercalcemia" are listed among the exact synonyms, but there is an another version of the name with 'idiopathic' in  Related synonyms. 
Likewise the SCTID and CUIs mapped as x-refs (or exactMatches) are jumbled by name/concept and mapping in UMLS:
SCTID: 34225008 | "Idiopathic hypercalcemia of infancy" | UMLS CUI: C0268080
UMLS: C4329374 | "Autosomal recessive infantile hypercalcemia" 
SCTID: 276645004 | "Infantile hypercalcemia" | UMLS CUI: C0475732 (NOTE this is also where UMLS maps the HPO term 
HP:0008250 "Infantile hypercalcemia"
NCIT: C129734 | "Autosomal recessive infantile hypercalcemia" | UMLS CUI: C4329374

Would it make sense to have all the Idiopathic names as Related if Mondo is saying this term exactly matches ORPHA:300547 "Autosomal recessive infantile hypercalcemia" ? 
Or even better still to keep this term is broad, but with Related names of all inheritance types (sporadic/idiopathic, included), rather than exact matches? This would be in closer alignment with mapping to SCTID 276645004 and allow for additional, specific children as needed in the future.

**Comment by ahamosh** [comment] 2022-03-08 16:12
I am confused.  Isn't this parent term for AR infantile hypercalcemia?  Other forms of inheritance would be separate and a higher node of inherited infantile hypercalcemia would be needed, right?

**Comment by kanems** [comment] 2022-03-08 16:38
Yes, @ahamosh, this term is the parent for hypercalcemia, infantile 1 and 2. The problem is we may have merged too many concepts/names into one Uber-parent: http://purl.obolibrary.org/obo/MONDO_0000212 is named "hypercalcemia, infantile" and, based on the Xrefs and ExactMatches above, seems to encompass a generic concept as well as the AR sub-group and Idiopathic subtype(s).

**Comment by nicolevasilevsky** [comment] 2022-04-20 00:48
@sabrina and I are looking into this and based on our google searches, we are under the impression that the idiopathic form of this disease is historical and was perhaps named as such before the genes were discovered (see: https://medlineplus.gov/genetics/condition/idiopathic-infantile-hypercalcemia/#causes).

We noted that the idiopathic synonyms are exact and historic and discouraged (deprecated).

It seems like all the evidence suggested the inheritance is AR, so I think it's okay to leave those synonyms as such? If any new evidence of a different type of inheritance arises, we can revise accordingly.

@kanems please reopen if anything is needed. :)

**Closed** 2022-04-22 17:42 UTC
Labels: high priority, OMIM, effort-M
