### ISSUE TITLE
Remove floating classes from mondo.owl etc

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#3953] opened 2021-11-05 16:26 UTC
Remove all classes from Mondo.owl that are floating around (have no label and are under thing).

@nicolevasilevsky you can bring this up at our next 1:1 if you want

**Comment by nicolevasilevsky** [comment] 2021-11-11 17:42
duplicate of https://github.com/monarch-initiative/mondo/issues/2034

**Closed by nicolevasilevsky** 2021-11-11 17:42 UTC
Labels: duplicate
