### ISSUE TITLE
[Obsolete] monogenic disease

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/mondo#722] opened 2019-05-31 01:21 UTC
**Mondo term (ID and Label)**
Monogenic disease

**Reason for deprecation**
Redundant 

**Suggested replacement or term to consider**
Inherited genetic disease

**Comment by cmungall** [comment] 2020-02-17 19:47
I think we need a stronger reason for obsoletion. It's not strictly redundant with its parent, as inherited can encompass both monogenic and polygenic.

Perhaps the reason for obsoletion is that it's not useful to bake in mono-vs-poly into the hierarchy, it's better to leave this to gene-disease associations?

But this leads to the question of where mono vs poly is curated. Can this be obtained from the omim g2d associations? Orphanet? Is clingen curating this? Perhaps there is value in retaining this info in mondo?

It certainly presents challenges. E.g. how would we classify https://www.omim.org/entry/608133? Would we split this into mono and di forms?

**Comment by nicolevasilevsky** [comment] 2020-02-17 23:24
@mellybelly do you want to weigh in on this?
Or @pnrobinson?

**Comment by pnrobinson** [comment] 2020-02-18 01:13
Current status
1. Monogenic disease is a child of inherited genetic disease. This is correct, because say digenic disease is also a child of inherited genetic disease
2. The problem is that most of the monogenic diseases in Mondo are not children of monogenic disease.
Things to consider
a. There are people who say that no disease is truly monogenic (because diseases have modifying genes etc etc), and the reality is that there is a spectrum of pathogenesis from nearly 100% monogenic to polygenic. Also, we do not always know whether a certain case is day digenic/triallelic or actually just plain autosomal recessive (Bardet Biedl example)
b. "monogenic" is a useful concept for family counseling but not for many other clinical management decisions
c. It may be better to choose other axes of primary hierarchy.
d. Inherited genetic disease is also not a good parent term, because many of the diseases can occur sporadically and are thus not inherited for all or even for most patients.
e. It would be good to ask Ada about here advice. I think that Mendelian is a better parent concept than inherited genetic disease, but I am not sure where would would place this few diseases that are clearly digenic.

**Comment by maglott** [comment] 2020-02-18 13:06
re: https://www.omim.org/entry/608133
@ahamosh  should certainly comment, but when NCBI  and UMLS incorporate data  from OMIM,
the 'included' titles are processed as a distinct entity, without an equivalence to the MIM number. (albeit with a relationship indicating 'included'). So yes, split.

**Comment by ahamosh** [comment] 2020-02-18 14:06
Sorry for the delay. I was off-line for a couple of days.  First, to Donna's comment, an included entry in an OMIM entry is a separate entity.  Digenic is not the same as Monogenic.  I think that Digenic can be included under Mendelian.  Digenic can look like recessive inheritance or like something weird. Beyond DIgenic, I think that you get into complex and not strictly Mendelian inheritance.  I think that all diseases are a combination of gene(s) and environment, but certainly Mendelian diseases have a large effect from a single gene and very rarely from two.

**Comment by nicolevasilevsky** [comment] 2020-03-07 02:06
@pnrobinson @cmungall @mellybelly 

Do we have an action item here? Should we proceed with obsoleting monogenic disease?

**Comment by pnrobinson** [comment] 2020-03-07 05:54
@ahamosh would it be possible to schedule a call to go over the hierarchy here and discuss the optimal hierarchy? But I think you are saying that "Mendelian disease" would be the best term here, which would work well for me.

**Comment by nicolevasilevsky** [comment] 2020-05-29 16:41
To do:
- [ ] obsolete monogenic disease and add 'consider' 'inherited genetic disease'

**Comment by mellybelly** [comment] 2020-06-01 20:54
yes my idea was to obsolete and have monogenic/polygenic be inferred from the annotations - but obviously don't want disrupt until there is a good alternative pipeline for creating this classification.

**Comment by pnrobinson** [comment] 2020-06-01 20:55
@mellybelly  It would be good to have more documentation about the plans for annotations like this. Are you referring to existing annotations or to logical definitions for Mondo classes or something else?

**Comment by mellybelly** [comment] 2020-06-01 20:56
a future world where we have a mondo-phenotype-gene-envo-treatment model :-)

**Comment by mellybelly** [comment] 2020-06-01 20:56
maybe this ticket was premature in lieu of that

**Comment by nicolevasilevsky** [comment] 2020-07-17 21:58
I created a super ticket for this, so I am going to close this ticket.

**Closed by nicolevasilevsky** 2020-07-17 21:58 UTC
Labels: blocked, obsolete
