### ISSUE TITLE
[Obsolete] MONDO:0002013 lymphangioma and NTR  'lymphatic malformation'

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/mondo#6769] opened 2023-10-16 19:42 UTC
**Mondo term (ID and Label)**
MONDO:0002013->lymphangioma

**Reason for deprecation**
"Several different terms were once used to describe conditions now grouped under the umbrella term “lymphatic malformations.” Such terms include cystic hygroma, lymphangioma, cavernous lymphangioma, cystic lymphangioma and lymphangioma circumscriptum. These terms have been abandoned because some of the outdated terms imply a relationship to cancer. Lymphatic malformations are not cancerous and there is no known risk of malignant transformation." [NORD ](https://rarediseases.org/rare-diseases/lymphatic-malformations/)

**Suggested term to consider**
I think that a NTR should be 'lymphatic malformation' BUT this is not an exact replacement as the hierarchy should be changed to not be in neoplams branches. Should be child of MONDO:0005833 lymphatic system disorder.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)
(https://orcid.org/0000-0001-7941-2961)

**Comment by nicolevasilevsky** [comment] 2024-01-02 19:14
@LCCarmody we already have an existing term labeled 'lymphatic malformation': MONDO:0019313. The definition is:
Primary lymphedema is caused by anatomic or functional defects in the lymphatic system, resulting in chronic swelling of body parts and lymphatic-system malformation.

This is equivalent to the OMIMPS: https://www.omim.org/phenotypicSeries/PS153100

I wonder if this existing term should be renamed to 'hereditary lymphatic malformation' and we should create the new term 'lymphatic malformation', as you suggested.

Do you think that all the current children of lymphangioma should be a child of 'lymphatic malformation'? 

- 'capillary lymphangioma'
- 'colonic lymphangioma'
- 'cystic hygroma'
- 'diffuse lymphatic malformation'
- 'Gorham-Stout disease'
- lymphangioendothelioma
- 'lymphedema-posterior choanal atresia syndrome'
- 'macrocystic lymphatic malformation'
- 'microcystic lymphatic malformation'
- 'mixed cystic lymphatic malformation'
- 'multifocal lymphangioendotheliomatosis-thrombocytopenia syndrome'
- 'skin lymphangioma'

cc @sabrinatoro

**Comment by LCCarmody** [comment] 2024-01-03 13:53
from a cursory look, all the lymphangiomas should also be looked at and possibly obsoleted as well. But this probably needs to be teased out as 'cystic hygroma' is said to be a synonym for lymphangioma at least with one resource (https://www.hopkinsmedicine.org/health/conditions-and-diseases/cystic-hygroma#:~:text=A%20cystic%20hygroma%20%E2%80%94%20or%20lymphangioma,fluid%20and%20white%20blood%20cells.). Its current textual def says neoplasm, but I am not certain that it is. Maybe this is an area that experts could weigh in?

**Comment by nicolevasilevsky** [comment] 2024-01-03 18:00
I think it's a good idea to get expert feedback, I certainly don't have expertise in this area. I am reassigning to Sabrina.

**Comment by twhetzel** [comment] 2024-02-09 01:24
I add this to the agenda for the next Domain Expert call.

**Comment by twhetzel** [comment] 2024-06-28 05:02
After review of these terms, given their xrefs to terms in other disease ontologies and that they are included in rare subsets, they will not be obsoleted.

**Closed by twhetzel** 2024-06-28 05:02 UTC
Labels: New term request, obsolete, on list, Ada/Peter
