### ISSUE TITLE
MONDO:0006361 & MONDO:0008231 Peyronie's disease [Merge]

### ISSUE THREAD

**Issue by kanems** [monarch-initiative/mondo#7142] opened 2024-01-18 14:03 UTC
**Mondo term (ID and Label)**
MONDO:0006361 penile fibromatosis

**Reason for deprecation**
These two terms share synonyms and X-ref/match to same NCIT term. UMLS treats them as synonyms on C0030848

**Term to be merged with**
MONDO:0008231 Peyronie's disease
**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by sabrinatoro** [comment] 2024-01-30 22:13
I am adding this term on the merge list, but **do not merge** until we have confirmed that these terms represent the same concept (at first view, they are "related" to each other, but more research is required in order to make a decision.

**Comment by twhetzel** [comment] 2024-03-22 21:03
@sabrinatoro since this ticket is tagged with "medical input needed" does it need to wait until then to be merged or is my review sufficient?

**Comment by sabrinatoro** [comment] 2024-03-22 21:10
@twhetzel If you have reviewed the issue and you are confident with what needs to be done (ie you don't need "medical input"), you can proceed. 
Please remove the "medical input needed" tag, and add a comment to document that someone (you) has reviewed this issue and agreed with the request.

**Comment by twhetzel** [comment] 2024-03-22 21:13
Thanks, tag removed. I had already commented above that I reviewed this and the two terms seem the same to me.

**Closed** 2024-03-26 20:25 UTC
Labels: merge, on list
