### ISSUE TITLE
[Merge] IDDM1 and type 1 diabetes mellitus

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#4892] opened 2022-05-02 15:24 UTC
**Mondo term (ID and Label)**
MONDO:0005147/type 1 diabetes mellitus 
MONDO:0009100/IDDM 1

**Reason for deprecation**
I don't see any definition to justify treating IDDM1 as a subtype of type 1 diabetes mellitus.  I know that OMIM treats IDDM1 as an included title for T1D, but I am not certain of the distinction.  There are papers that seem to treat these as the same entity.
https://pubmed.ncbi.nlm.nih.gov/15505007/.  Should these be lumped?

**Term to be merged with**

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by maglott** [comment] 2022-05-02 15:29
I should have done one more lookup i guess.  I see that IDDM1 is the subset based on the MHC.   
https://www.nature.com/articles/6363875; maybe that could be added to the definition.

**Comment by nicolevasilevsky** [comment] 2022-05-03 23:27
@sabrinatoro could you review this ticket? 

I think these are the action items, let me know if you agree:

It seems like this class is equiv to OMIM:222100 and I think this Mondo class is referring to an included entry in [OMIM:222100](https://omim.org/entry/222100): 
name: DIABETES MELLITUS, INSULIN-DEPENDENT, 1, INCLUDED
synonym: IDDM1

- [ ]  I think that 'insulin-dependent diabetes mellitus 1' is a separate class (it is currently a synonym in Mondo, it is an 'included' entry in OMIM) and should be a new class in Mondo
- [ ] 'type 1 diabetes mellitus' should be a broad synonym
- [ ] 'diabetes mellitus, insulin-dependent' should be a narrow synonym 
- [ ] 'diabetes mellitus, type 1' should be a narrow synonym
- [ ] 'IDDM' should be a narrow synonym
- [ ] 'IDDM1' should be an exact synonym
- [ ] 'juvenile-onset diabetes' should be a narrow synonym
- [ ] Proposed definition of IDDM1: Any type 1 diabetes mellitus that is caused by variation in genes located in the MHC complex on chromosome 6p21.3. [dbxref: PMID:12140742]

**Comment by sabrinatoro** [comment] 2022-05-04 19:46
@nicolevasilevsky 
I agree with the definition and with "insulin-dependent diabetes mellitus 1" being a separate class. I am not sure to which terms the synonyms above refer.

I think the ontology should be:
- type 1 diabetes mellitus (MONDO:0005147)
 - Mondo:EquivalentTo : OMIM:222100
 - 'diabetes mellitus, insulin-dependent' should be exact synonym
 - 'IDDM' should be exact synonym
 - 'IDDM1' should be narrow synonym

- IDDM 1 (MONDO:0009100) 
 - is a more specific type 1 diabetes, and should be a child of type 1 diabetes mellitus
 -  'diabetes mellitus, insulin-dependent' should be broad synonym
 - 'IDDM' should be broad synonym
 - OMIM:222100 should/could probably also be Mondo:EquivalentTo (since the omim term seems to include both the "broad" type 1 diabetes, and the more specific IDDM1), however we might have issue of proxi-merge (or reverse proxi-merge).

**Comment by nicolevasilevsky** [comment] 2022-06-10 21:07
@sabrinatoro I merged the PR b/c I was having trouble viewing your changes on your branch for some reason.

I agree with your suggestions above. Currently OMIM:222100 is equiv to IDDM 1 (MONDO:0009100), I am going to make it relatedTo and make  OMIM:222100  equiv to type 1 diabetes mellitus (MONDO:0005147)

**Closed** 2022-06-11 00:11 UTC
Labels: definition, user request
