### ISSUE TITLE
[NTR] New lung terms - from Mattias and Christina

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/mondo#5261] opened 2022-08-10 16:59 UTC
Peter and I met with pulmonary experts Mattias and Christina. We'll add new lung terms from this [spreadsheet](https://docs.google.com/spreadsheets/d/1Sz47Dk5TZvUh4xMEd6GqfHNqQcmI6BgW/edit#gid=361015257).

Related to #3026 

cc @pnrobinson

**Comment by nicolevasilevsky** [comment] 2022-08-10 18:32
@pnrobinson 
is pulmonary hypoplasia the same as MONDO:0020419 'pulmonary artery hypoplasia'?

**Comment by pnrobinson** [comment] 2022-08-10 18:40
pulmonary hypoplasia means undergrowth of the lung, so it is different!

**Comment by nicolevasilevsky** [comment] 2022-08-10 20:39
Thanks @pnrobinson!

**Comment by nicolevasilevsky** [comment] 2022-08-16 15:37
From Christina:
Immunodeficiency, autosomal recessive, due to ZNFX1 deficiency: same as in OMIM 619644; citation: PMID: [33872655](https://pubmed.ncbi.nlm.nih.gov/33872655). I will add this as a synonym to MONDO:0030491

**Comment by nicolevasilevsky** [comment] 2022-08-16 15:49
From Christina:
immunodeficiency, due to IKZF3 deficiency: Has also an OMIM ID: 619437; citation: PMID: 34155405. i added this a synonym of MONDO:0030333 'immunodeficiency 84'

**Comment by nicolevasilevsky** [comment] 2022-09-21 22:54
talked to Ada on 09/21/22- I will send PMIDs to her for any terms that are not in OMIM and they will consider adding them and then we can map them in Mondo

**Comment by nicolevasilevsky** [comment] 2022-10-03 23:28
this is done, will be available in the November release

**Comment by cmungall** [comment] 2024-08-21 14:22
It looks like the genes were not added? E.g.

id: MONDO:0800136
name: non-severe combined immunodeficiency due to COPG1 deficiency
def: "Any non-severe combined immunodeficiency caused by a deficiency in the COPG1 gene." [PMID:33529166]
subset: gard_rare {source="MONDO:GARD"}
subset: nord_rare {source="MONDO:NORD"}
subset: rare
is_a: MONDO:0018814 {source="https://orcid.org/0000-0002-7371-8158", source="https://orcid.org/0000-0003-0113-912X"} ! non-SCID combined immunodeficiency
relationship: RO:0002573 HP:0000007 {source="https://orcid.org/0000-0002-7371-8158", source="https://orcid.org/0000-0003-0113-912X"} ! has modifier Autosomal recessive inheritance
property_value: IAO:0000233 "https://github.com/monarch-initiative/mondo/issues/5261" xsd:anyURI

But no link to COPG1?

**Comment by nicolevasilevsky** [comment] 2024-08-21 15:18
to do: 
- [ ] import COPG1 gene
- [ ] add axiom to MONDO:0800136 non-severe combined immunodeficiency due to COPG1 deficiency

@twhetzel can you take care of this?

**Comment by twhetzel** [comment] 2024-11-04 02:26
Sorry, I missed this one! Yes, I can do that. I'll add this to the Nov board so it's tracked in a release board, but will be in Dec release.

There is now a [gSheet](https://docs.google.com/spreadsheets/d/1UME3pTeR42hwNt1I6RPl0nvJKVfTIeJqhx80laAlD50/edit?gid=0#gid=0) to add any imports needed when we do this step for the Mondo Release SOP.

**Comment by twhetzel** [comment] 2024-11-06 03:35
Importing the gene is blocked by an [issue](https://github.com/monarch-initiative/mondo/issues/8308) where the `refresh-merged` is running out of memory.

**Closed** 2024-11-26 21:57 UTC
Labels: New term request, user request
