### ISSUE TITLE
inborn errors or metabolism

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/mondo#1589] opened 2020-05-26 17:35 UTC
**Mondo term (ID Label)**
https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0019052

**Bug/Typo/Error description**

At least half of the children of this term are not actually inborn errors or metabolism. The term "inborn error of metabolism" is not precisely defined, but it is well described here:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6331353/

**Comment by nicolevasilevsky** [comment] 2021-02-17 19:03
related #239

**Comment by nicolevasilevsky** [comment] 2021-03-04 23:36
@jiaola this is not high priority at the moment, but I think the action item here to use some kind of tagging tool like Google OpenRefine to automatically map the parents and subclasses to Mondo IDs? (Name matching), as mentioned in #239

**Comment by nicolevasilevsky** [comment] 2022-11-29 00:48
this is a duplicate of https://github.com/monarch-initiative/mondo/issues/4985

I'll close this in favor of the other ticket.

**Closed by nicolevasilevsky** 2022-11-29 00:48 UTC
Labels: duplicate, help wanted, superclass
