### ISSUE TITLE
[Obsolete] MONDO:0012233 Li Fraumeni Syndrome 2

### ISSUE THREAD

**Issue by Megfrone** [monarch-initiative/mondo#6269] opened 2023-05-15 17:45 UTC
**Mondo term (ID and Label)**
MONDO:0012233 Li Fraumeni Syndrome 2

**Reason for deprecation**
Li Fraumeni syndrome is not caused by variants in the CHEK2 gene

**Suggested term to consider**
Remove ID completely. This would also likely mean that Li Fraumeni Syndrome and Li Fraumeni syndrome 1 could be merged into one mondo ID. There is currently confusion as both are used interchangeably.

**Your nano-attribution (ORCID)**
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment] 2023-05-15 17:48
duplicate of https://github.com/monarch-initiative/mondo/issues/6260

**Comment by nicolevasilevsky** [comment] 2023-05-15 17:49
@Megfrone Thanks for the ticket, we'll be sure to address this. We like to leave requests for obsoletion open for at least two months to give curators an opportunity to update their annotations. We will obsolete this on or after Aug 01.

**Comment by nicolevasilevsky** [comment] 2023-07-20 17:59
to do: Obsolete type 2 and merge type 1 into general class- keep the parent class - we are "unsplitting" (lumping back together)

discussed on curation call with @sabrinatoro and Eric Sid

**Comment by Megfrone** [comment] 2023-07-26 17:33
Thank you. Please note you will likely need to keep a CHEK2 MONDO ID as there is a genetic syndrome involving deleterious variants in CHEK2 and breast and colorectal cancer risk. This just has nothing to do with LFS.

**Comment by nicolevasilevsky** [comment] 2023-07-26 18:13
Hi @Megfrone 
there are these two diseases in Mondo, which are equivalent to OMIM terms that implicate CHEK2

- MONDO:0016419 'hereditary breast carcinoma', equiv to https://omim.org/entry/114480
- MONDO:0005575 'colorectal cancer', equiv to https://omim.org/entry/114500

I don't think any other action is needed here, but please reopen this ticket if so.

**Closed by nicolevasilevsky** 2023-07-26 18:13 UTC
Labels: obsolete, on list
