### ISSUE TITLE
Revise definitions

### ISSUE THREAD

**Issue by matentzn** [monarch-initiative/mondo#2912] opened 2021-04-11 11:26 UTC
The following (40) definitions appear broken:

- [x] MONDO:0007989
- [x] MONDO:0008863
- [x] MONDO:0008908
- [x] MONDO:0009397 - def: Neonatal severe primary hyperparathyroidism (NSHPT) is characterized by severe hypercalcemia (> 3.5 mM) from birth and associated with major hyperparathyroidism.
- [x] MONDO:0010998 - def: SSR4-CDG is a form of congenital disorders of N-linked glycosylation characterized by neurologic abnormalities (global developmental delay in language, social skills and fine and gross motor development, intellectual disability, hypotonia, microcephaly, seizures/epilepsy), facial dysmorphism (deep set eyes, large ears, hypoplastic vermillion of upper lip, large mouth with widely spaced teeth), feeding problems often due to chewing difficulties and aversion to food with certain textures, failure to thrive, gastrointestinal abnormalities (reflux or vomiting) and strabismus. The disease is caused by mutations in the gene SSR4 (Xq28).
- [x] MONDO:0011257 - def: MPI-CDG is a form of congenital disorders of N-linked glycosylation, characterized by cyclic vomiting, profound hypoglycemia, failure to thrive, liver fibrosis, gastrointestinal complications (protein-losing enteropathy with hypoalbuminaemia, life-threatening intestinal bleeding of diffuse origin), and thrombotic events (protein C and S deficiency, low anti-thrombine III levels), whereas neurological development and cognitive capacity is usually normal. The clinical course is variable even within families. The disease is caused by loss of function of the gene MPI (15q24.1).
- [x] MONDO:0011291 - def: A form of congenital disorders of N-linked glycosylation characterized by feeding problems, mild-to-moderate neurologic involvement with hypotonia, poor head control, developmental delay, ataxia, strabismus, and seizures, ranging from febrile convulsions to epilepsy. Retinal degeneration has also been reported. A minority of patients show other manifestations, particularly intestinal (such as protein-losing enteropathy) and liver involvement. The disease is caused by loss of function mutations of the gene ALG6 (1p31.3).
- [x] MONDO:0011629 - def: MOGS-CDG is a form of congenital disorders of N-linked glycosylation characterized by generalized hypotonia, craniofacial dysmorphism (prominent occiput, short palpebral fissures, long eyelashes, broad nose, high arched palate , retrognathia), hypoplastic genitalia, seizures, feeding difficulties, hypoventilation, severe hypogammaglobulinemia with generalized edema, and increased resistance to particular viral infections (particularly to enveloped viruses). The disease is caused by loss-of-function mutations in the gene MOGS (2p13.1).
- [x] MONDO:0011783
- [x] MONDO:0011933
- [x] MONDO:0011969
- [x] MONDO:0012052
- [x] MONDO:0012117
- [x] MONDO:0012783
- [x] MONDO:0013349
- [x] MONDO:0013789
- [x] MONDO:0013870
- [x] MONDO:0014044
- [x] MONDO:0014248
- [x] MONDO:0014271
- [ ] MONDO:0015561
- [x] MONDO:0015571
- [ ] MONDO:0015989
- [x] MONDO:0016015
- [x] MONDO:0016379
- [x] MONDO:0017049
- [x] MONDO:0017227
- [x] MONDO:0017228
- [x] MONDO:0017802
- [x] MONDO:0018339
- [x] MONDO:0018349
- [x] MONDO:0018495
- [x] MONDO:0018956
- [x] MONDO:0019105
- [x] MONDO:0019357
- [x] MONDO:0019450
- [x] MONDO:0019549
- [x] MONDO:0044255
- [x] MONDO:0044266

These seem to be the remaining ones from our big push last year to fix definitions that broke during import.

**Comment by nicolevasilevsky** [comment] 2021-05-07 13:30
The workflow for this is:
1. Look up the Mondo ID
2. Find the Orphanet xref
3. Look up the Orphanet term in [OLS](https://www.ebi.ac.uk/ols/index) (for example [Orphanet:79330](https://www.ebi.ac.uk/ols/search?q=Orphanet%3A79330&groupField=iri&exact=on&start=0)
4. Copy the definition of the Orphanet term 
5. Replace the definition for the Mondo term in Protege
6. Check off the box above when you've replaced the def in Protege on your branch

Note - I've created a few branches for this ticket already, so I suggest you name your branch issue-2912c (or 2912d, ie whatever letter hasn't been used yet in the alphabet)

**Comment by kallia-p** [comment] 2021-05-14 18:46
@nicolevasilevsky The following definition that you added as an example above is different to the one I found for MONDO:0010998 in OLS so I presume it's incorrect.
MONDO:0010998 - def: SSR4-CDG is a form of congenital disorders of N-linked glycosylation characterized by neurologic abnormalities (global developmental delay in language, social skills and fine and gross motor development, intellectual disability, hypotonia, microcephaly, seizures/epilepsy), facial dysmorphism (deep set eyes, large ears, hypoplastic vermillion of upper lip, large mouth with widely spaced teeth), feeding problems often due to chewing difficulties and aversion to food with certain textures, failure to thrive, gastrointestinal abnormalities (reflux or vomiting) and strabismus. The disease is caused by mutations in the gene SSR4 (Xq28).
Instead I added the definition in OLS see http://www.orpha.net/ORDO/Orphanet_79321

**Comment by nicolevasilevsky** [comment] 2021-05-14 19:04
Hi @kallia-p I am not sure what you mean
MONDO:0010998 is ALG3-CDG
The xref is Orphanet:79321
This is the def in OLS: https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_79321

A form of congenital disorders of N-linked glycosylation characterized by severe neurological involvement, including hypotonia, developmental delay, intellectual disability, postnatal microcephaly, and progressive brain and cerebellar atrophy. Epilepsy with hypsarrythmia is frequently reported. Additional features that may be observed include failure to thrive, arthrogryposis multiplex congenita (AMC), vision impairment (optic atrophy, iris coloboma) and facial dysmorphism (hypertelorism with a broad nasal bridge, large and thick ears, thin lips, micrognathia). The disease is caused by loss of function mutations of the gene ALG3 (3q27.3).

**Comment by kallia-p** [comment] 2021-05-14 19:45
MONDO:0014044 existing definition below is the same as in Orphanet http://www.orpha.net/ORDO/Orphanet_289553
#64258;at nares, Cupid's bow upper lip vermilion, and small, low-set, posteriorly rotated ears), in addition to cleft palate, conductive hearing loss, heart defects (atrial or ventricular septal defect) and mild developmental delay/intellectual disability.
definition bug?
see

**Comment by nicolevasilevsky** [comment] 2021-05-14 20:09
@kallia-p You can download the orphanet owl file here:
http://www.orphadata.org/cgi-bin/index.php

and open the file in Protege and look for definitions there too

**Comment by nicolevasilevsky** [comment] 2021-05-14 20:10
although in the case above, the definition looks wrong in their ontology too. I would report the bug to Orphanet and we should just delete the definition in Mondo.

**Comment by kallia-p** [comment] 2021-05-14 20:15
@nicolevasilevsky In this case shall I change the dbxref to OMIM:615102 and delete the Orphanet?

**Comment by nicolevasilevsky** [comment] 2021-05-14 20:17
Yes, exactly!

**Comment by kallia-p** [comment] 2021-05-14 20:24
@nicolevasilevsky Thanks for prompt replies. I am halfway through the defs and will resume on Mon or Tue next week plus other high priority tickets.

**Comment by kallia-p** [comment] 2021-05-17 13:18
@nicolevasilevsky MONDO:0015561 term 'aleukemic mast cell leukemia' is obsolete see OLS http://www.orpha.net/ORDO/Orphanet_158799
![image](https://user-images.githubusercontent.com/77484553/118493160-b47b2700-b718-11eb-827f-036a1cb1854b.png)
They suggest to use http://www.orpha.net/ORDO/Orphanet_98851 with label: Mast cell leukemia
In Mondo we have this term MONDO:0020334 as a parent of 'aleukemic mast cell leukemia'.
But it looks like the definition in Mondo is not current: 
Definition1: Mast cell leukemia is a malignant form of systemic mastocytosis (SM) characterized, most of the time, by the presence of circulating mast cells.
whereas in OLS and Orphanet is: 
Definition 2: A very rare malignant systemic mastocytosis (SM) characterized by a huge infiltration of bone marrow, and often of blood, by abnormal mast cells (MC) which frequently manifests with organ dysfunction (liver, spleen, peritoneum, bones, and marrow).
Suggested workflow for this term:
1. Make aleukemic mast cell leukemia obsolete as per your video instructions. 
2. Fix or leave the definition broken? I can't see the definition of an obsolete Orphanet term in Orphanet or OLS.
3. Update the 'mast cell leukemia' def as per definition 2.

**Comment by kallia-p** [comment] 2021-05-17 13:31
MONDO:0015989 dbxref Orphanet:1864 is also obsolete and they they point to http://www.orpha.net/ORDO/Orphanet_555877
![image](https://user-images.githubusercontent.com/77484553/118495606-42f0a800-b71b-11eb-9e87-a961f065e901.png)
![image](https://user-images.githubusercontent.com/77484553/118496066-b09cd400-b71b-11eb-9210-f4e5e966c519.png)

Disease definition is OLS is missing but I can take it from Orphanet:
https://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=555877
A rare genetic cardiac malformation characterized by progressive myxomatous degeneration predominantly of the mitral valve (but not uncommonly with multivalvular involvement), presenting as valve thickening and dysfunction with variable stenosis, prolapse, and/or regurgitation, and potentially resulting in lethal heart failure. Hyperextensible skin and joint hypermobility have been reported in some patients. Hemizygous males display a more severe phenotype than heterozygous females.

**Comment by kallia-p** [comment] 2021-05-17 14:25
@nicolevasilevsky PR is still draft but only the two terms above need so once I get your reply I will convert it. Pls let me know if you think we should open separate tickets to make these terms obsolete.

**Comment by nicolevasilevsky** [comment] 2021-05-18 03:22
Hi @kallia-p -
MONDO_0015561 'aleukemic mast cell leukemia' should be merged with MONDO_0020334 'mast cell leukemia'. I'll create a ticket. We notify the Mondo users by email before obsoleting any classes and give them 2 weeks to reply or note any issues. I have a merging workflow that is described [here](https://mondo.readthedocs.io/en/latest/editors-guide/merging-and-obsoleting/#merge-using-owltools).

For now, can you delete the broken definition for MONDO_0015561 'aleukemic mast cell leukemia'?

Thank you!

**Comment by nicolevasilevsky** [comment] 2021-05-18 03:32
I created a ticket to merge MONDO:0015989 'congenital valvular dysplasia' too, thanks @kallia-p!

**Comment by kallia-p** [comment] 2021-05-18 08:28
@nicolevasilevsky Many thanks Nicole! PR is ready for review.

**Closed** 2021-05-19 18:15 UTC
Labels: definition, effort-XL, good first issue, high priority
