### ISSUE TITLE
revisit Testicular regression syndrome  and 46,XY sex reversal 11 and management of other OMIM alternate names

### ISSUE THREAD

**Issue by maglott** [monarch-initiative/mondo#5768] opened 2023-01-02 14:01 UTC
When OMIM provides an alternate name for a disorder, when is that alternate name used to support an entry in Mondo distinct from the primary name in OMIM.
For the example of TRS/SRXY11, I see that Orphanet (https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Expert=983) gives the gene as DHX37 for TRS, as OMIM does for SRX&11, so I am not certain these are considered distinct entities.

**Comment by maglott** [comment] 2023-01-02 14:17
See also:  MONDO:0800195 and MONDO:0009279

**Comment by nicolevasilevsky** [comment] 2023-02-08 03:48
@maglott it looks like we split these out a while back because Orphanet did not have a gene associated with their term, but it looks like this has changed. I think MONDO:8000015 '46,XY sex reversal 11' and MONDO:8000017 'testicular regression syndrome' should be merged.

**Comment by nicolevasilevsky** [comment] 2023-02-08 03:54
> See also: MONDO:0800195 and MONDO:0009279

'achalasia-alacrima syndrome' is an included entry in OMIM, so we split it out into a separate class. Included entries are intended to be distinct diseases.

**Closed** 2023-04-29 02:16 UTC
Labels: on list, user request
