### ISSUE TITLE
hereditary hemophagocytic lymphohistiocytosis

### ISSUE THREAD

**Issue by galyea123** [monarch-initiative/mondo#7437] opened 2024-03-20 13:39 UTC
hereditary hemophagocytic lymphohistiocytosis MONDO:0015541

I believe this should not be linked to the group, (Primary hemophagocytic lymphohistiocytosis), only to the disorder: Familial hemophagocytic lymphohistiocytosis https://www.orpha.net/en/disease/detail/540 (the synonyms should also be fixed)

Thank you,

Gioconda Alyea

**Comment by sabrinatoro** [comment] 2024-03-27 15:46
My research: 

the Mondo term 'hereditary hemophagocytic lymphohistiocytosis' (MONDO:0015541) refers to "an instance of hemophagocytic lyphohistiocytosis that is caused by an inherited genomic modification".

[Orpha:540](https://www.orpha.net/en/disease/detail/540?name=540&mode=orpha) refers to be also inherited, and maps to multiple OMIM terms. Therefore this terms represents a concept similar to MONDO:0015541


[Orpha:158038](https://www.orpha.net/en/disease/detail/158038?name=158038&mode=orpha) refers to a grouping term, and based on OLS, it groups multiple other orphanet term, included orpha:540 (above), "immunodeficiency syndrome with hypopigmentation" (which has been obsoleted in Mondo), and X-linked lymphoproliferative disease (which is also a child of MONDO:0015541, and based on the definition would be hereditary).
![Screenshot 2024-03-27 at 08 34 28](https://github.com/monarch-initiative/mondo/assets/12737987/ec66c0be-6264-47f1-8bb4-425191974f2a)

Note: I do not know whether it is correct to say that "X-linked lymphoproliferative disease" is a child of 'hereditary hemophagocytic lymphohistiocytosis' (MONDO:0015541).

I agree with the current annotation in Mondo and think we should keep the current 
'hereditary hemophagocytic lymphohistiocytosis' (MONDO:0015541) is equivalent to Orpha:540, and Orpha:540 should be the preferred x-ref.

TO DO (I think)
- IF 'hereditary hemophagocytic lymphohistiocytosis' (MONDO:0015541) is correctly a child of 'hereditary hemophagocytic lymphohistiocytosis' (MONDO:0015541), then I think it is correct to keep the other equivalent MONDO:0015541 - Orpha:158038.
- IF 'hereditary hemophagocytic lymphohistiocytosis' (MONDO:0015541) is NOT a child of 'hereditary hemophagocytic lymphohistiocytosis' (MONDO:0015541), then we should exclude Orpha:158038 in Mondo as a grouping term that is not in scope in Mondo (the grouping might be based on having the features of 'hereditary hemophagocytic lymphohistiocytosis')

**Comment by sabrinatoro** [comment] 2024-03-28 19:09
**2024-03-28 Mondo expert call:** 
- Ada reviewed the phenotypic series for 'lymphoproliferative syndrome' (OMIMPS:308240) and 'hereditary hemophagocytic lymphohistiocytosis' (OMIMPS:267700), and compared the features for the disease included in these PS to determine whether "X-linked lymphoproliferative disease" is a type of 'hereditary hemophagocytic lymphohistiocytosis'. It looks like these were not the same. 
- Based on PMID:35748970: x-linked lymphoproliferative diseases are grouped under '7. Susceptibility to EBV and Lymphoproliferative Conditions', and not hemophagocytic lymphohistiocytosis


TO DO: 
- [ ] exclude Orpha:158038 in Mondo as a grouping term that is not in scope in Mondo
- [ ] exclude subclass of 'hereditary hemophagocytic lymphohistiocytosis' for 'X-linked lymphoproliferative syndrome'

**Comment by sabrinatoro** [comment] 2024-05-14 14:14
@twhetzel 

https://github.com/monarch-initiative/mondo-ingest/blob/main/src/ontology/config/ordo_exclusions.tsv

**Comment by twhetzel** [comment] 2024-06-10 22:14
@sabrinatoro PR submitted to `mondo-ingest` https://github.com/monarch-initiative/mondo-ingest/pull/562

**Comment by twhetzel** [comment] 2024-06-17 07:17
The remaining step Sabrina requested (to update a file in `mondo-ingest`) is done and merged into `main`.

**Closed by twhetzel** 2024-06-17 07:17 UTC
Labels: xref, user request
