### ISSUE TITLE
developmental and epileptic encephalopathy

### ISSUE THREAD

**Issue by rebecca-siegert** [monarch-initiative/mondo#332] opened 2018-09-06 12:54 UTC
## Preferred term label

Epileptic and developmental encephalopathy

## Textual definition

Individuals with GABRB3 variants have a range of developmental delay and epileptic encephalopathy phenotypes. Seizure onset ranges from early infantile to childhood. Intellectual disability is variable in presence and severity.

## Suggested parent term

Complex neurodevelopmental disorder (MONDO:0100038)

## Additional Analysis of disease

Individuals, both male and female, have been reported with variants in the GABRB3 gene. De novo and familial cases have been reported, with mostly missense and a few nonsense variants identified as causative. These patients have been described in the literature as having a range of phenotypes characterized as epileptic encephalopathy, Lennox-Gastaut syndrome, Dravet syndrome-like, and childhood absence epilepsy. Severity of intellectual disability is variable among reported probands, as is the age of onset of seizure phenotypes. In one case of epileptic encephalopathy, for example, the individual presented with severe intellectual disability while seizures onset at 12 years old (27476654). Additionally, individuals have been reported with the same de novo missense variants, and have been described with varying phenotypes (27476654, 26544041, 26704558, 26993267, 26645412). 

## References

Myers et al. 2016 (27476654), Zhang et al. 2015 (26544041), Bagnall et al. 2016 (26704558), Trump et al. 2016 (26993267), Papandreou et al. 2016 (26645412)

**Comment by nicolevasilevsky** [comment] 2018-09-12 22:08
@rebecca-siegert we have this term: MONDO_0014921 'epileptic encephalopathy, early infantile, 43; EIEE43'
Text definition: Any early infantile epileptic encephalopathy in which the cause of the disease is a mutation in the GABRB3 gene.

Let me know if I can close this issue.

**Comment by rebecca-siegert** [comment] 2018-09-13 15:30
@nicolevasilevsky After discussing the available literature for epilepsy cases concerning the GABRB3 gene with an expert physician in the epilepsy field, we concluded that the available term 'epileptic encephalopathy, early infantile, 43; EIEE43' does not encompass the phenotypic range seen in the literature. I think I was misleading and incorrect in including the GABRB3 gene name in the Textual Definition, my apologies. My goal is to create a disease term ID related to GABRB3, but that is not entirely exclusive to this gene. The "Additional Analysis of Disease" provides more information about the need for this new MONDO term, but there may be genes assessed in the future to which this term would apply. I will write a follow-up comment with a revised Textual definition.

**Comment by rebecca-siegert** [comment] 2018-09-13 15:30
A range of developmental delay and epileptic encephalopathy phenotypes. Seizure onset is variable and intellectual disability is variable in presence and severity.

**Comment by nicolevasilevsky** [comment] 2018-09-13 15:51
Thanks for the additional info, @rebecca-siegert!

**Closed** 2018-10-15 00:32 UTC
Labels: New term request, epilepsy
