### ISSUE TITLE
Fatty acyl-coA reductase 1 dysregulation[NTR]

### ISSUE THREAD

**Issue by Mohan-Shruthi** [monarch-initiative/mondo#2493] opened 2020-12-21 15:45 UTC
**Preferred term label:** fatty acyl-coA reductase 1 dysregulation

**Synonyms** none

**Definition (free text, please give PubMed ID, if applicable, in format PMID:#######)** autosomal dominant neurological disorder that results in uncontrolled synthesis of ether lipids (PMID: 33239752)

**Parent term (use [OLS](https://www.ebi.ac.uk/ols/ontologies/mondo), or your favorite ontology browser)** MONDO:0017986 (disorder of plasmalogen biosynthesis)

**Children terms (if applicable)** none

**Your nano-attribution (ORCID)** ClinGen Peroxisomal Disorders gene curation expert panel
If you don't have an ORCID, you can sign up for one [here](https://orcid.org/)

**Comment by nicolevasilevsky** [comment] 2021-01-20 18:50
@Mohan-Shruthi - I added a parent 'nervous system disorder' and added the annotation that this disease is caused by dysfunction in the FAR1 gene. If any of this is incorrect, please let me know. This will be available in the next release around Feb 01.

**Comment by Mohan-Shruthi** [comment] 2021-01-21 16:17
Hi Nicole,

Thank you for the update. I’ll let the group know and get back to you with any additional comments.

Thanks,
Shruthi
-----------------------------
Shruthi Mohan, Ph.D.
ClinGen Biocurator, Berg Lab | Department of Genetics | UNC – Chapel Hill
Desk: 919-843-3549

**Comment by nicolevasilevsky** [comment] 2021-01-21 19:23
Thanks @Mohan-Shruthi.
I added this term and closed this ticket, but please do let me know if any changes are needed. Thank you!

**Closed** 2021-01-21 19:22 UTC
Labels: New term request, high priority
